[Service]
Environment="JAVA_OPTS=-Djava.awt.headless=true -Dspring.config.location=classpath:/application.yml,optional:file:/etc/tomcat10/slss/application.properties"
EnvironmentFile=-/etc/tomcat10/slss/jdbc.properties
EnvironmentFile=-/etc/tomcat10/slss/security.properties
EnvironmentFile=-/etc/tomcat10/slss/queue.properties
