package com.slss.api;

import com.slss.domain.LoginBackgroundAsset; import com.slss.repository.LoginBackgroundAssetRepository; import com.slss.service.AuditService;
import jakarta.servlet.http.HttpServletRequest; import jakarta.transaction.Transactional; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import org.springframework.web.server.ResponseStatusException;
import javax.imageio.ImageIO; import java.awt.image.BufferedImage; import java.io.*; import java.security.*; import java.time.Instant; import java.util.*;

@RestController @RequestMapping("/api/v1/settings/branding/backgrounds")
public class LoginBackgroundAssetController {
 private static final long MAX_BYTES=5_000_000; private static final Set<String> TYPES=Set.of("image/png","image/jpeg","image/webp");
 private final LoginBackgroundAssetRepository repo; private final AuditService audit;
 public LoginBackgroundAssetController(LoginBackgroundAssetRepository r,AuditService a){repo=r;audit=a;}
 public record BackgroundAsset(Long id,String fileName,String mimeType,long fileSize,int width,int height,String url,int sortOrder){ static BackgroundAsset of(LoginBackgroundAsset a){return new BackgroundAsset(a.getId(),a.getFileName(),a.getMimeType(),a.getFileSize(),a.getWidth(),a.getHeight(),"/api/v1/settings/branding/backgrounds/"+a.getId()+"/content",a.getSortOrder());} }
 @GetMapping public List<BackgroundAsset> list(){return repo.findByEnabledTrueOrderBySortOrderAscCreatedAtAsc().stream().map(BackgroundAsset::of).toList();}
 @GetMapping("/{id}/content") public ResponseEntity<byte[]> content(@PathVariable Long id){var a=repo.findById(id).filter(LoginBackgroundAsset::isEnabled).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"背景资源不存在"));return ResponseEntity.ok().cacheControl(CacheControl.maxAge(java.time.Duration.ofHours(1)).cachePublic()).eTag(a.getSha256()).contentType(MediaType.parseMediaType(a.getMimeType())).body(a.getImageData());}
 @PostMapping(consumes=MediaType.MULTIPART_FORM_DATA_VALUE) @PreAuthorize("hasAuthority('PERM_MANAGE_SYSTEM')") @Transactional public BackgroundAsset upload(@RequestPart("file") MultipartFile file,@RequestParam(defaultValue="0") int sortOrder,java.security.Principal actor,HttpServletRequest req){if(file==null||file.isEmpty()||file.getSize()>MAX_BYTES)throw bad("背景图片大小须为1B-5MB");String type=Optional.ofNullable(file.getContentType()).orElse("").toLowerCase(Locale.ROOT);if(!TYPES.contains(type))throw bad("仅支持PNG/JPEG/WEBP背景图片");try{byte[] bytes=file.getBytes();BufferedImage image=ImageIO.read(new ByteArrayInputStream(bytes));if(image==null||image.getWidth()>8192||image.getHeight()>8192)throw bad("背景图片格式或尺寸无效");var a=new LoginBackgroundAsset();a.setFileName(Optional.ofNullable(file.getOriginalFilename()).orElse("background"));a.setMimeType(type.equals("image/jpg")?"image/jpeg":type);a.setFileSize(bytes.length);a.setWidth(image.getWidth());a.setHeight(image.getHeight());a.setSha256(sha(bytes));a.setSortOrder(Math.max(0,sortOrder));a.setCreatedBy(actor==null?"system":actor.getName());a.setImageData(bytes);a.setUpdatedAt(Instant.now());repo.save(a);audit.record(a.getCreatedBy(),"LOGIN_BACKGROUND_UPLOAD","BRANDING_ASSET",String.valueOf(a.getId()),a.getFileName(),req.getRemoteAddr(),true);return BackgroundAsset.of(a);}catch(IOException e){throw bad("背景图片无法解析");}}
 @DeleteMapping("/{id}") @PreAuthorize("hasAuthority('PERM_MANAGE_SYSTEM')") @Transactional public void remove(@PathVariable Long id,java.security.Principal actor,HttpServletRequest req){var a=repo.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"背景资源不存在"));a.setEnabled(false);a.setUpdatedAt(Instant.now());repo.save(a);audit.record(actor==null?"system":actor.getName(),"LOGIN_BACKGROUND_DELETE","BRANDING_ASSET",String.valueOf(id),a.getFileName(),req.getRemoteAddr(),true);}
 private ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);} private String sha(byte[] b){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(b));}catch(Exception e){throw new IllegalStateException(e);}}
}
