package com.slss.api;
import com.slss.domain.*; import com.slss.repository.RepairOrderRepository; import com.slss.repository.AssetRepository; import com.slss.service.RepairOrderService; import com.slss.service.TenantScopeService; import jakarta.validation.Valid; import jakarta.validation.constraints.NotBlank; import jakarta.validation.constraints.Size; import org.springframework.web.bind.annotation.*; import java.util.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.data.domain.*;
@RestController @RequestMapping("/api/v1/service-orders") public class OrderController {
 private final RepairOrderRepository repo; private final RepairOrderService service; private final AssetRepository assets; private final TenantScopeService tenantScope; public OrderController(RepairOrderRepository repo,RepairOrderService service,AssetRepository assets,TenantScopeService tenantScope){this.repo=repo;this.service=service;this.assets=assets;this.tenantScope=tenantScope;}
 public record CreateRequest(@NotBlank String orderNumber,@NotBlank String customerName,@NotBlank String faultDescription,String machineSn){}
 public record UpdateRequest(@Size(max=255) String customerName,@Size(max=20000) String faultDescription,@Size(max=255) String machineSn,@Size(max=200000) String receivedConfigJson,@Size(max=20000) String actualFaultDescription){}
 @GetMapping @PreAuthorize("hasAnyAuthority('PERM_VIEW_ORDERS','PERM_MANAGE_ORDERS')") public List<RepairOrderResponse> list(){return repo.findAll().stream().filter(o->tenantScope.canAccess(o.getTenant())).map(o->RepairOrderResponse.from(o,resolveModel(o.getMachineSn()))).toList();}
 @GetMapping("/page") @PreAuthorize("hasAnyAuthority('PERM_VIEW_ORDERS','PERM_MANAGE_ORDERS')") public PageResponse<RepairOrderResponse> page(@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="50") int size){
  var pageable=PageRequest.of(Math.max(0,page),Math.min(Math.max(1,size),200),Sort.by(Sort.Direction.DESC,"createdAt"));
  var ids=tenantScope.currentTenantIds();
  var result=tenantScope.isSystemAdmin()?repo.findAll(pageable):(ids.isEmpty()?repo.findByTenantIsNull(pageable):repo.findByTenant_IdIn(ids,pageable));
  return PageResponse.of(result.map(o->RepairOrderResponse.from(o,resolveModel(o.getMachineSn()))));
 }
 @GetMapping("/{id}") @PreAuthorize("hasAnyAuthority('PERM_VIEW_ORDERS','PERM_MANAGE_ORDERS')") public RepairOrderResponse get(@PathVariable Long id){var o=repo.findById(id).orElseThrow();tenantScope.requireAccess(o.getTenant());return RepairOrderResponse.from(o,resolveModel(o.getMachineSn()));}
 @PostMapping @PreAuthorize("hasAuthority('PERM_MANAGE_ORDERS')") public RepairOrderResponse create(@Valid @RequestBody CreateRequest r){var o=new RepairOrder();o.setOrderNumber(r.orderNumber());o.setCustomerName(r.customerName());o.setFaultDescription(r.faultDescription());o.setMachineSn(r.machineSn());o.setTenant(tenantScope.tenantForCreate(r.customerName()));var saved=service.create(o);return RepairOrderResponse.from(saved,resolveModel(saved.getMachineSn()));}
 @PatchMapping("/{id}") @PreAuthorize("hasAuthority('PERM_MANAGE_ORDERS')") public RepairOrderResponse update(@PathVariable Long id,@Valid @RequestBody UpdateRequest r){var existing=repo.findById(id).orElseThrow();tenantScope.requireAccess(existing.getTenant());var saved=service.update(id,r.customerName(),r.faultDescription(),r.machineSn(),r.receivedConfigJson(),r.actualFaultDescription());return RepairOrderResponse.from(saved,resolveModel(saved.getMachineSn()));}
 private String resolveModel(String machineSn){if(machineSn==null||machineSn.isBlank())return null;return assets.findByMachineSnIgnoreCase(machineSn).map(Asset::getModel).orElse(null);}
}
