package com.slss.api;
import com.slss.repository.*; import com.slss.service.AuditService; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException; import org.springframework.http.HttpStatus; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.context.SecurityContextHolder; import jakarta.servlet.http.HttpServletRequest; import java.util.*; import java.util.concurrent.ConcurrentHashMap;
@RestController @RequestMapping("/api/v1/portal") @PreAuthorize("hasAnyAuthority('PERM_VIEW_ORDERS','PERM_VIEW_PRODUCTION')")
public class PortalController {
 private final RepairOrderRepository orders; private final AssetRepository assets; private final LifecycleEventRepository lifecycle; private final OrderStatusHistoryRepository history; private final RepairTestRepository tests; private final RepairLogisticsRepository logistics; private final RepairReportRepository reports; private final AuditService audit; private final UserRepository users; private final CustomerTenantRepository tenants; private final Map<String,Window> limits=new ConcurrentHashMap<>();
 public PortalController(RepairOrderRepository o,AssetRepository a,LifecycleEventRepository l,OrderStatusHistoryRepository h,RepairTestRepository t,RepairLogisticsRepository g,RepairReportRepository r,AuditService audit,UserRepository users,CustomerTenantRepository tenants){orders=o;assets=a;lifecycle=l;history=h;tests=t;logistics=g;reports=r;this.audit=audit;this.users=users;this.tenants=tenants;}
 @GetMapping("/assets/{machineSn}") public Map<String,Object> get(@PathVariable String machineSn,HttpServletRequest request){String actor=request.getUserPrincipal()==null?"anonymous":request.getUserPrincipal().getName();if(!allow(actor+"|"+request.getRemoteAddr())){audit.record(actor,"PORTAL_RATE_LIMIT","ASSET",machineSn,"查询频率超限",request.getRemoteAddr(),false);throw new ResponseStatusException(HttpStatus.TOO_MANY_REQUESTS,"查询过于频繁，请稍后再试");}var asset=assets.findByMachineSnIgnoreCase(machineSn).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"资产不存在或无权访问"));if(!SecurityContextHolder.getContext().getAuthentication().getAuthorities().stream().anyMatch(a->a.getAuthority().equals("PERM_MANAGE_SYSTEM"))){var user=users.findByUsernameAndStatus(actor,"ACTIVE").orElseThrow(()->new ResponseStatusException(HttpStatus.FORBIDDEN,"用户未绑定客户租户"));var allowed=tenants.findActiveIdsByUserId(user.getId());if(asset.getTenant()==null||!allowed.contains(asset.getTenant().getId()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"无权访问该客户设备");}var os=orders.findByMachineSnIgnoreCaseOrderByCreatedAtDesc(machineSn);var result=new LinkedHashMap<String,Object>();var ad=new LinkedHashMap<String,Object>();ad.put("machineSn",asset.getMachineSn());ad.put("model",Optional.ofNullable(asset.getModel()).orElse(""));ad.put("contractNo",Optional.ofNullable(asset.getContractNo()).orElse(""));ad.put("invoiceDate",asset.getInvoiceDate());result.put("asset",ad);result.put("orders",os.stream().map(x->{var m=new LinkedHashMap<String,Object>();m.put("id",x.getId());m.put("orderNumber",x.getOrderNumber());m.put("status",x.getStatus());m.put("faultDescription",x.getFaultDescription());m.put("createdAt",x.getCreatedAt());return m;}).toList());result.put("lifecycle",lifecycle.findByAssetIdOrderByOccurredAtAsc(asset.getId()));var ids=os.stream().map(x->x.getId()).toList();result.put("tests",ids.stream().flatMap(id->tests.findByOrderId(id).stream()).toList());result.put("logistics",ids.stream().flatMap(id->logistics.findByOrderId(id).stream()).toList());result.put("reports",ids.stream().map(reports::findByOrderId).flatMap(Optional::stream).toList());result.put("statusHistory",os.isEmpty()?List.of():history.findByOrderIdOrderByCreatedAtAsc(os.get(0).getId()));audit.record(actor,"PORTAL_ASSET_QUERY","ASSET",machineSn,"Portal 资产查询",request.getRemoteAddr(),true);return result;}
 private boolean allow(String key){long now=System.currentTimeMillis()/60000;var w=limits.compute(key,(k,v)->v==null||v.window!=now?new Window(now):v);return ++w.count<=60;} private static final class Window{final long window;int count;Window(long w){window=w;}}
}
