package com.slss.api;
import com.fasterxml.jackson.databind.*; import com.slss.domain.QualityInspectionTemplate; import com.slss.repository.QualityInspectionTemplateRepository; import com.slss.service.AuditService; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import java.security.Principal; import java.time.Instant; import java.util.*;
@RestController @RequestMapping("/api/v1/quality/inspection-templates") @PreAuthorize("hasAnyAuthority('PERM_MANAGE_SCAN_TEMPLATE','PERM_MANAGE_SYSTEM')")
public class QualityInspectionTemplateController { final QualityInspectionTemplateRepository repo; final ObjectMapper mapper; final AuditService audit; public QualityInspectionTemplateController(QualityInspectionTemplateRepository r,ObjectMapper m,AuditService a){repo=r;mapper=m;audit=a;}
 record Request(String customerName,String dispatchOrderNo,List<Map<String,Object>> stages){}
 private Map<String,Object> dto(QualityInspectionTemplate t)throws Exception{var m=new LinkedHashMap<String,Object>();m.put("id",t.getId());m.put("customerName",t.getCustomerName());m.put("machineModel",t.getDispatchOrderNo());m.put("stages",mapper.readValue(t.getStagesJson(),Object.class));m.put("createdAt",t.getCreatedAt());m.put("updatedAt",t.getUpdatedAt());return m;}
 @GetMapping public List<Map<String,Object>> list() { try{return repo.findByActiveTrueOrderByCreatedAtDesc().stream().map(t->{try{return dto(t);}catch(Exception e){throw new IllegalStateException(e);}}).toList();}catch(Exception e){throw new IllegalStateException("检验模板读取失败",e);} }
 @PostMapping public Map<String,Object> create(@RequestBody Request r,Principal p)throws Exception{return save(null,r,p);}
 @PutMapping("/{id}") public Map<String,Object> update(@PathVariable Long id,@RequestBody Request r,Principal p)throws Exception{return save(id,r,p);}
 @DeleteMapping("/{id}") public void delete(@PathVariable Long id,Principal p){var t=repo.findById(id).orElseThrow(()->new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.NOT_FOUND,"检验模板不存在"));t.setActive(false);repo.save(t);audit.record(p==null?"system":p.getName(),"QUALITY_TEMPLATE_DELETE","QUALITY_TEMPLATE",String.valueOf(id),"删除检验单模板",null,true);}
 private Map<String,Object> save(Long id,Request r,Principal p)throws Exception{if(r.customerName()==null||r.customerName().isBlank()||r.dispatchOrderNo()==null||r.dispatchOrderNo().isBlank())throw new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.BAD_REQUEST,"客户名称和派工单号不能为空"); if(r.stages()==null||r.stages().size()!=3)throw new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.BAD_REQUEST,"必须包含初检、复检、终检三个阶段");var t=id==null?new QualityInspectionTemplate():repo.findById(id).orElseThrow();if(id==null&&repo.findByCustomerNameIgnoreCaseAndDispatchOrderNoIgnoreCase(r.customerName().trim(),r.dispatchOrderNo().trim()).isPresent())throw new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.CONFLICT,"该客户和派工单号的检验模板已存在");t.setCustomerName(r.customerName().trim());t.setDispatchOrderNo(r.dispatchOrderNo().trim());t.setStagesJson(mapper.writeValueAsString(r.stages()));t.setCreatedBy(p==null?"system":p.getName());t.setUpdatedAt(Instant.now());var saved=repo.save(t);audit.record(t.getCreatedBy(),id==null?"QUALITY_TEMPLATE_CREATE":"QUALITY_TEMPLATE_UPDATE","QUALITY_TEMPLATE",String.valueOf(saved.getId()),"保存检验单模板",null,true);return dto(saved);}
}
