package com.slss.api;
import com.slss.domain.*; import com.slss.repository.*; import com.slss.service.SalesInitiationService; import jakarta.transaction.Transactional; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/v1/sales-initiations/{initiationId}/requirements") @PreAuthorize("hasAuthority('PERM_MANAGE_SALES')")
public class SalesRequirementController {
 private final SalesInitiationService sales; private final ServerRequirementRepository servers; private final SoftwareRequirementRepository software;
 public SalesRequirementController(SalesInitiationService s,ServerRequirementRepository sr,SoftwareRequirementRepository sw){sales=s;servers=sr;software=sw;}
 public record ServerRequest(String serverModel,@Min(1) int quantity,String cpuRequirement,String memoryRequirement,String storageRequirement,String networkRequirement,String customDescription){}
 public record ServerResponse(Long id,Long initiationId,String serverModel,int quantity,String cpuRequirement,String memoryRequirement,String storageRequirement,String networkRequirement,String customDescription){}
 public record SoftwareRequest(String osName,String osVersion,String middleware,String databaseRequirement,String licenseRequirement,String securityRequirement){}
 public record SoftwareResponse(Long id,Long initiationId,String osName,String osVersion,String middleware,String databaseRequirement,String licenseRequirement,String securityRequirement){}
 private ServerResponse dto(ServerRequirement x){return new ServerResponse(x.getId(),x.getInitiationId(),x.getServerModel(),x.getQuantity(),x.getCpuRequirement(),x.getMemoryRequirement(),x.getStorageRequirement(),x.getNetworkRequirement(),x.getCustomDescription());}
 private SoftwareResponse dto(SoftwareRequirement x){return new SoftwareResponse(x.getId(),x.getInitiationId(),x.getOsName(),x.getOsVersion(),x.getMiddleware(),x.getDatabaseRequirement(),x.getLicenseRequirement(),x.getSecurityRequirement());}
 @GetMapping("/servers") public List<ServerResponse> servers(@PathVariable Long initiationId){sales.get(initiationId);return servers.findByInitiation_Id(initiationId).stream().map(this::dto).toList();}
 @PostMapping("/servers") @Transactional public ServerResponse addServer(@PathVariable Long initiationId,@Valid @RequestBody ServerRequest r){var x=new ServerRequirement();x.setInitiation(sales.requireDraft(initiationId));x.setServerModel(r.serverModel());x.setQuantity(r.quantity());x.setCpuRequirement(r.cpuRequirement());x.setMemoryRequirement(r.memoryRequirement());x.setStorageRequirement(r.storageRequirement());x.setNetworkRequirement(r.networkRequirement());x.setCustomDescription(r.customDescription());return dto(servers.save(x));}
 @DeleteMapping("/servers/{id}") @Transactional public void deleteServer(@PathVariable Long initiationId,@PathVariable Long id){sales.requireDraft(initiationId);servers.deleteByIdAndInitiation_Id(id,initiationId);}
 @GetMapping("/software") public List<SoftwareResponse> software(@PathVariable Long initiationId){sales.get(initiationId);return software.findByInitiation_Id(initiationId).stream().map(this::dto).toList();}
 @PostMapping("/software") @Transactional public SoftwareResponse addSoftware(@PathVariable Long initiationId,@Valid @RequestBody SoftwareRequest r){var x=new SoftwareRequirement();x.setInitiation(sales.requireDraft(initiationId));x.setOsName(r.osName());x.setOsVersion(r.osVersion());x.setMiddleware(r.middleware());x.setDatabaseRequirement(r.databaseRequirement());x.setLicenseRequirement(r.licenseRequirement());x.setSecurityRequirement(r.securityRequirement());return dto(software.save(x));}
 @DeleteMapping("/software/{id}") @Transactional public void deleteSoftware(@PathVariable Long initiationId,@PathVariable Long id){sales.requireDraft(initiationId);software.deleteByIdAndInitiation_Id(id,initiationId);}
}
