package com.slss.api;
import com.slss.domain.*; import com.slss.service.SalesInitiationService; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import java.time.*; import java.util.*;
@RestController @RequestMapping("/api/v1/sales-initiations") public class SalesInitiationController {
 private final SalesInitiationService service; public SalesInitiationController(SalesInitiationService s){service=s;}
 public record CreateRequest(@NotBlank String customerName,@NotBlank String projectName,@Min(1) int quantity,LocalDate requestedDeliveryDate,String deliveryLocation,String priority,String businessBackground,String technicalSummary,String softwareSummary,Long salesOwner){}
 public record TransitionRequest(@NotNull SalesInitiationStatus targetStatus,String comment){}
 public record Response(Long id,String initiationNo,String customerName,String projectName,int quantity,LocalDate requestedDeliveryDate,String deliveryLocation,String priority,SalesInitiationStatus status,String businessBackground,String technicalSummary,String softwareSummary,Long salesOwner,Instant createdAt,Instant updatedAt){}
 private Response dto(SalesInitiation x){return new Response(x.getId(),x.getInitiationNo(),x.getCustomerName(),x.getProjectName(),x.getQuantity(),x.getRequestedDeliveryDate(),x.getDeliveryLocation(),x.getPriority(),x.getStatus(),x.getBusinessBackground(),x.getTechnicalSummary(),x.getSoftwareSummary(),x.getSalesOwner(),x.getCreatedAt(),x.getUpdatedAt());}
 @GetMapping @PreAuthorize("hasAnyAuthority('PERM_MANAGE_SALES','PERM_MANAGE_PROCUREMENT')") public List<Response> list(){return service.list().stream().map(this::dto).toList();}
 @GetMapping("/{id}") @PreAuthorize("hasAnyAuthority('PERM_MANAGE_SALES','PERM_MANAGE_PROCUREMENT')") public Response get(@PathVariable Long id){return dto(service.get(id));}
 @PostMapping @PreAuthorize("hasAuthority('PERM_MANAGE_SALES')") public Response create(@Valid @RequestBody CreateRequest r){var x=new SalesInitiation();x.setCustomerName(r.customerName());x.setProjectName(r.projectName());x.setQuantity(r.quantity());x.setRequestedDeliveryDate(r.requestedDeliveryDate());x.setDeliveryLocation(r.deliveryLocation());x.setPriority(r.priority());x.setBusinessBackground(r.businessBackground());x.setTechnicalSummary(r.technicalSummary());x.setSoftwareSummary(r.softwareSummary());x.setSalesOwner(r.salesOwner());return dto(service.create(x));}
 @PostMapping("/{id}/transitions") @PreAuthorize("hasAnyAuthority('PERM_MANAGE_SALES','PERM_MANAGE_PROCUREMENT')") public Response transition(@PathVariable Long id,@Valid @RequestBody TransitionRequest r){return dto(service.transition(id,r.targetStatus(),r.comment()));}
 @PostMapping("/{id}/submit") @PreAuthorize("hasAuthority('PERM_MANAGE_SALES')") public Response submit(@PathVariable Long id){return dto(service.transition(id,SalesInitiationStatus.SUBMITTED,"提交销售立项"));}
}
