package com.slss.service;

import com.slss.domain.LoginCaptchaChallenge; import com.slss.repository.LoginCaptchaChallengeRepository; import com.slss.repository.SystemSettingRepository; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.awt.*; import java.awt.image.BufferedImage; import java.io.*; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.util.*; import javax.imageio.ImageIO;

@Service
public class CaptchaService {
 private final LoginCaptchaChallengeRepository repo; private final SystemSettingRepository settings; private final SecureRandom random=new SecureRandom();
 public CaptchaService(LoginCaptchaChallengeRepository r,SystemSettingRepository s){repo=r;settings=s;}
 public record Status(boolean enabled, boolean required, int failures, int triggerAfterFailures){}
 public record Challenge(String token,String image,int expiresInSeconds){}
 private String setting(String key,String fallback){return settings.findById(key).map(x->x.getSettingValue()).filter(v->v!=null&&!v.isBlank()).orElse(fallback);}
 private int integer(String key,int fallback){try{return Integer.parseInt(setting(key,String.valueOf(fallback)));}catch(Exception e){return fallback;}}
 public Status status(String username,Long failures){boolean enabled=Boolean.parseBoolean(setting("login.captcha.enabled","true"));int threshold=Math.max(1,integer("login.captcha.triggerAfterFailures",3));int count=failures==null?0:failures.intValue();return new Status(enabled,enabled&&count>=threshold,count,threshold);}
 @Transactional public Challenge issue(String username,String ip){int seconds=Math.max(30,Math.min(900,integer("login.captcha.expireSeconds",120)));int max=Math.max(1,Math.min(10,integer("login.captcha.maxAttempts",5)));int len=Math.max(4,Math.min(8,integer("login.captcha.length",5)));String alphabet="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";StringBuilder answer=new StringBuilder();for(int i=0;i<len;i++)answer.append(alphabet.charAt(random.nextInt(alphabet.length())));String token=UUID.randomUUID().toString().replace("-","");var c=new LoginCaptchaChallenge();c.setId(token);c.setUsername(username);c.setIpAddress(ip==null?"":ip);c.setAnswerHash(hash(answer.toString()));c.setExpiresAt(Instant.now().plusSeconds(seconds));c.setMaxAttempts(max);repo.save(c);return new Challenge(token,render(answer.toString()),seconds);}
 @Transactional public boolean verify(String token,String username,String ip,String answer){if(token==null||answer==null||answer.isBlank())return false;var c=repo.findById(token).orElse(null);if(c==null||c.isConsumed()||c.getExpiresAt().isBefore(Instant.now())||!Objects.equals(c.getUsername(),username)||!Objects.equals(c.getIpAddress(),ip)){return false;}if(c.getAttempts()>=c.getMaxAttempts()){c.setConsumed(true);repo.save(c);return false;}c.setAttempts(c.getAttempts()+1);boolean ok=constantEquals(c.getAnswerHash(),hash(normalize(answer)));if(ok)c.setConsumed(true);else if(c.getAttempts()>=c.getMaxAttempts())c.setConsumed(true);repo.save(c);return ok;}
 private String normalize(String s){return Boolean.parseBoolean(setting("login.captcha.caseSensitive","false"))?s.trim():s.trim().toUpperCase(Locale.ROOT);}
 private String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 private boolean constantEquals(String a,String b){return MessageDigest.isEqual(a.getBytes(StandardCharsets.US_ASCII),b.getBytes(StandardCharsets.US_ASCII));}
 private String render(String text){try{BufferedImage image=new BufferedImage(240,72,BufferedImage.TYPE_INT_RGB);Graphics2D g=image.createGraphics();g.setColor(new Color(248,250,252));g.fillRect(0,0,240,72);g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);for(int i=0;i<8;i++){g.setColor(new Color(5,150,105,80));g.drawLine(random.nextInt(240),random.nextInt(72),random.nextInt(240),random.nextInt(72));}g.setFont(new Font("SansSerif",Font.BOLD,36));g.setColor(new Color(15,23,42));g.drawString(text,24,49);g.dispose();ByteArrayOutputStream out=new ByteArrayOutputStream();ImageIO.write(image,"png",out);return "data:image/png;base64,"+Base64.getEncoder().encodeToString(out.toByteArray());}catch(IOException e){throw new IllegalStateException(e);}}
}
