import React, { useEffect, useMemo, useRef, useState } from 'react';
import { useTheme } from '../components/ThemeContext';
import { api } from '../services/apiClient';
import { analyzeFault } from '../services/aiService';
import { Activity, AlertTriangle, BrainCircuit, CheckCircle2, Clock3, Cpu, Maximize2, RefreshCw, Wrench, X } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

const chartColorsByTheme = { blue: ['#1d4ed8', '#2563eb', '#059669', '#f59e0b', '#dc2626', '#7c3aed'], purple: ['#6d28d9', '#7c3aed', '#059669', '#f59e0b', '#dc2626', '#2563eb'], green: ['#047857', '#059669', '#2563eb', '#f59e0b', '#dc2626', '#7c3aed'], orange: ['#c2410c', '#ea580c', '#059669', '#f59e0b', '#dc2626', '#7c3aed'], slate: ['#334155', '#475569', '#059669', '#f59e0b', '#dc2626', '#7c3aed'] } as const;
type DetailType = 'completed' | 'unfinished' | 'repair' | 'week-completed' | 'week-unfinished' | 'week-repair' | null;

const Dashboard: React.FC = () => {
  const { theme, themeConfig } = useTheme();
  const chartColors = chartColorsByTheme[theme];
  const [summary, setSummary] = useState<any>({});
  const [statistics, setStatistics] = useState<any>({});
  const [production, setProduction] = useState<any>({ customers: [] });
  const [alerts, setAlerts] = useState<any>({ overdue: [], recurring: [] });
  const [error, setError] = useState('');
  const [refreshing, setRefreshing] = useState(false);
  const [lastUpdated, setLastUpdated] = useState<Date | null>(null);
  const [detailType, setDetailType] = useState<DetailType>(null);
  const [aiText, setAiText] = useState('');
  const [analyzing, setAnalyzing] = useState(false);
  const [displayMode, setDisplayMode] = useState<'standard' | 'large'>(() => { try { return localStorage.getItem('slss_dashboard_mode') === 'large' ? 'large' : 'standard'; } catch { return 'standard'; } });
  const rootRef = useRef<HTMLDivElement>(null);

  const refresh = async (silent = false) => {
    if (!silent) setRefreshing(true); setError('');
    const results = await Promise.allSettled([api.dashboardProduction(), api.dashboardSummary(), api.dashboardStatistics(), api.dashboardAlerts()]);
    const [p, s, st, a] = results;
    if (p.status === 'fulfilled') setProduction(p.value || {});
    if (s.status === 'fulfilled') setSummary(s.value || {});
    if (st.status === 'fulfilled') setStatistics(st.value || {});
    if (a.status === 'fulfilled') setAlerts(a.value || {});
    const failed = results.filter(x => x.status === 'rejected') as PromiseRejectedResult[];
    if (failed.length) setError(`部分数据加载失败：${failed.map(x => x.reason?.message || '接口异常').join('；')}`); else setLastUpdated(new Date());
    if (!silent) setRefreshing(false);
  };
  useEffect(() => { refresh(); const timer = window.setInterval(() => refresh(true), 30000); return () => window.clearInterval(timer); }, []);
  const stats = { total: summary.totalOrders || 0, pending: summary.pending || 0, checking: summary.checking || 0, closed: summary.closed || 0, assets: summary.assets || 0 };
  const customerData = statistics.customers || [];
  const componentData = statistics.components || [];
  const productionCustomerData = (production.customers || []).map((x: any) => ({ name: x.customer || x.customerName || '未命名客户', 完工: Number(x.completed || 0), 未完工: Number(x.unfinished || 0), 维修: Number(x.repair || 0) })).slice(0, 12);
  const detailRows = detailType === 'completed' ? production.completedDevices : detailType === 'unfinished' ? production.unfinishedDevices : detailType === 'repair' ? production.repairDevices : detailType === 'week-completed' ? production.weekCompletedDevices : detailType === 'week-unfinished' ? production.weekUnfinishedDevices : production.weekRepairDevices;
  const detailGroups = useMemo(() => { const map = new Map<string, any>(); (detailRows || []).forEach((x: any) => { const key = `${x.customerName || '未知客户'}-${x.model || '未设置型号'}`; const item = map.get(key) || { customer: x.customerName || '未知客户', model: x.model || '未设置型号', quantity: 0 }; item.quantity += 1; map.set(key, item); }); return [...map.values()]; }, [detailRows]);
  const runAI = async () => { setAnalyzing(true); try { const result = await analyzeFault(`生产设备${production.total || 0}台，今日完工${production.completed || 0}台，待完工${production.unfinished || 0}台，逾期工单${alerts.overdue?.length || 0}条。请给出三条可执行运营建议。`, 'SLSS Operations'); setAiText(result.recommendation || result.summary || '暂无建议。'); } catch { setAiText('AI 分析暂不可用，请检查后端模型配置。'); } finally { setAnalyzing(false); } };
  const toggleLarge = () => { const next = displayMode === 'large' ? 'standard' : 'large'; setDisplayMode(next); try { localStorage.setItem('slss_dashboard_mode', next); } catch { /* ignore */ } };
  const fullscreen = async () => { try { if (document.fullscreenElement) await document.exitFullscreen(); else await rootRef.current?.requestFullscreen(); } catch { /* ignore */ } };
  const Kpi = ({ label, value, hint, icon: Icon, tone = 'text-[var(--color-primary)]', onClick }: any) => <button onClick={onClick} className="slss-kpi slss-card-hover w-full text-left"><div className="flex items-start justify-between"><div><p className="slss-kpi-label">{label}</p><p className={`slss-kpi-value mt-3 ${tone}`}>{value}</p></div><span className="theme-accent-soft rounded-xl border p-2.5"><Icon size={18} /></span></div><p className="mt-4 text-xs text-slate-500">{hint}</p></button>;
  return <div ref={rootRef} className={`dashboard-root min-h-full space-y-6 p-1 md:p-3 ${displayMode === 'large' ? 'dashboard-large min-h-screen' : ''}`}>
    {error && <div className="flex items-start justify-between gap-3 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><span><AlertTriangle className="mr-2 inline" size={16} />{error}</span><button aria-label="关闭错误提示" onClick={() => setError('')}><X size={16} /></button></div>}
    <section className="slss-card overflow-hidden border-0 bg-[var(--color-primary)] p-6 text-white shadow-lg md:p-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-emerald-300"><span className="slss-status-dot" />Live operations</div><h1 className="text-3xl font-bold tracking-tight md:text-4xl">生产运营总览</h1><p className="mt-3 max-w-xl text-sm leading-6 text-slate-200">把生产扫码、工单服务和交付风险集中到一个可执行的运营视图。</p></div><div className="flex flex-wrap items-center gap-2"><button onClick={toggleLarge} className="slss-btn-secondary border-white/20 bg-white/10 text-white hover:bg-white/20">{displayMode === 'large' ? '标准模式' : '大屏模式'}</button><button aria-label="全屏查看" onClick={fullscreen} className="slss-btn-secondary border-white/20 bg-white/10 text-white hover:bg-white/20"><Maximize2 size={15} />全屏</button><button onClick={() => refresh()} disabled={refreshing} className="slss-btn-secondary border-white/20 bg-white/10 text-white hover:bg-white/20"><RefreshCw size={15} className={refreshing ? 'animate-spin' : ''} />刷新</button></div></div><div className="mt-6 flex items-center justify-between border-t border-white/15 pt-4 text-xs text-slate-300"><span>当前主题：{themeConfig.name}</span><span>最后同步：{lastUpdated ? lastUpdated.toLocaleTimeString('zh-CN') : '同步中…'}</span></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Kpi label="生产设备" value={production.total || stats.assets} hint="当前扫码表设备总量" icon={Cpu} /><Kpi label="今日完工" value={production.completed || 0} hint="点击查看设备明细" tone="text-emerald-700" icon={CheckCircle2} onClick={() => setDetailType('completed')} /><Kpi label="待完工" value={production.unfinished || 0} hint="点击查看未完工明细" tone="text-amber-700" icon={Clock3} onClick={() => setDetailType('unfinished')} /><Kpi label="维修设备" value={production.repair || 0} hint="点击查看维修明细" tone="text-red-700" icon={Wrench} onClick={() => setDetailType('repair')} /><Kpi label="服务工单" value={stats.total} hint={`待处理 ${stats.pending} · 处理中 ${stats.checking}`} icon={Activity} /></section>
    <section className="grid gap-5 xl:grid-cols-[1.45fr_1fr]"><div className="slss-card p-5"><div className="mb-4 flex items-start justify-between"><div><h2 className="slss-section-title text-lg font-bold">客户交付进度</h2><p className="mt-1 text-xs text-slate-500">完工、未完工与维修设备按客户汇总</p></div><Activity className="text-[var(--color-secondary)]" size={20} /></div><div className="h-[300px]">{productionCustomerData.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={productionCustomerData} margin={{ top: 8, right: 10, left: -18, bottom: 8 }}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" /><XAxis dataKey="name" tick={{ fontSize: 11 }} /><YAxis allowDecimals={false} tick={{ fontSize: 11 }} /><Tooltip /><Legend /><Bar dataKey="完工" fill="#16a34a" radius={[4,4,0,0]} /><Bar dataKey="未完工" fill="#f59e0b" radius={[4,4,0,0]} /><Bar dataKey="维修" fill="#dc2626" radius={[4,4,0,0]} /></BarChart></ResponsiveContainer> : <div className="grid h-full place-items-center text-sm text-slate-500">暂无生产统计数据</div>}</div></div><div className="slss-card p-5"><div className="mb-4 flex items-start justify-between"><div><h2 className="slss-section-title text-lg font-bold">故障组件分布</h2><p className="mt-1 text-xs text-slate-500">维修事件按组件类型统计</p></div><Wrench className="text-red-600" size={20} /></div><div className="h-[300px]">{componentData.length ? <ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={componentData} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={100} label={({ name, percent }) => `${name} ${Math.round((percent || 0) * 100)}%`}>{componentData.map((_: any, i: number) => <Cell key={i} fill={chartColors[i % chartColors.length]} />)}</Pie><Tooltip /><Legend /></PieChart></ResponsiveContainer> : <div className="grid h-full place-items-center text-sm text-slate-500">暂无维修组件数据</div>}</div></div></section>
    <section className="slss-card p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="slss-section-title text-lg font-bold">生产数据</h2><p className="mt-1 text-xs text-slate-500">按日、按周查看生产交付结果</p></div><div className="flex gap-2"><button className="slss-btn-secondary" onClick={() => setDetailType('week-completed')}>本周完工</button><button className="slss-btn-secondary" onClick={() => setDetailType('week-unfinished')}>本周未完工</button><button className="slss-btn-secondary" onClick={() => setDetailType('week-repair')}>本周维修</button></div></div><div className="overflow-x-auto"><table className="slss-table"><thead><tr><th>客户</th><th>完工数量</th><th>未完工数量</th><th>维修数量</th></tr></thead><tbody>{(production.customers || []).map((x: any) => <tr key={x.customer || x.customerName}><td className="font-semibold text-slate-800">{x.customer || x.customerName || '未知客户'}</td><td className="font-mono text-emerald-700">{x.completed || 0}</td><td className="font-mono text-amber-700">{x.unfinished || 0}</td><td className="font-mono text-red-700">{x.repair || 0}</td></tr>)}</tbody></table>{!production.customers?.length && <div className="p-10 text-center text-sm text-slate-500">暂无生产数据</div>}</div></section>
    <section className="grid gap-5 xl:grid-cols-[1.25fr_1fr]"><div className="slss-card p-5"><div className="flex items-center justify-between"><div><h2 className="slss-section-title text-lg font-bold">服务风险信号</h2><p className="mt-1 text-xs text-slate-500">逾期与重复故障需要优先处理</p></div><AlertTriangle className="text-amber-600" size={20} /></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-amber-50 p-4"><p className="text-xs font-bold text-amber-700">SLA 逾期</p><p className="mt-2 font-mono text-3xl font-bold text-amber-900">{alerts.overdue?.length || 0}</p></div><div className="rounded-xl bg-red-50 p-4"><p className="text-xs font-bold text-red-700">重复故障</p><p className="mt-2 font-mono text-3xl font-bold text-red-900">{alerts.recurring?.length || 0}</p></div></div></div><div className="slss-card p-5"><div className="flex items-center justify-between"><div><h2 className="slss-section-title text-lg font-bold">AI 运营建议</h2><p className="mt-1 text-xs text-slate-500">基于当前后端统计快照生成</p></div><BrainCircuit className="text-[var(--color-secondary)]" size={20} /></div><button onClick={runAI} disabled={analyzing} className="slss-btn-primary mt-4 w-full"><BrainCircuit size={15} />{analyzing ? '分析中…' : '生成建议'}</button>{aiText && <p className="mt-4 whitespace-pre-wrap rounded-lg bg-slate-50 p-3 text-sm leading-6 text-slate-700">{aiText}</p>}</div></section>
    {detailType && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4" onClick={() => setDetailType(null)}><div className="slss-card max-h-[85vh] w-full max-w-4xl overflow-auto p-5" onClick={event => event.stopPropagation()}><div className="mb-4 flex items-center justify-between"><h2 className="slss-section-title text-xl font-bold">{detailType.startsWith('week-') ? '本周' : '今日'}{detailType.includes('completed') ? '完工' : detailType.includes('unfinished') ? '未完工' : '维修'}明细</h2><button aria-label="关闭明细" onClick={() => setDetailType(null)} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><X size={18} /></button></div><table className="slss-table"><thead><tr><th>客户名称</th><th>整机型号</th><th>整机数量</th></tr></thead><tbody>{detailGroups.map((x: any) => <tr key={`${x.customer}-${x.model}`}><td>{x.customer}</td><td>{x.model}</td><td className="font-mono font-bold text-[var(--color-secondary)]">{x.quantity}</td></tr>)}</tbody></table>{!detailGroups.length && <div className="p-10 text-center text-sm text-slate-500">暂无明细数据</div>}</div></div>}
    <footer className="flex flex-wrap items-center justify-between gap-2 border-t border-slate-200 pt-4 text-xs text-slate-500"><span>SLSS Lifecycle Operations</span><span>数据权限由当前登录角色控制</span></footer>
  </div>;
};
export default Dashboard;
