
import React, { useState, useEffect, useRef, useCallback } from 'react';
import { FileSpreadsheet, Save, Plus, Trash2, RefreshCw, Database, ScanLine, X, Volume2, VolumeX, Wifi, WifiOff, Cloud, Check, Loader2, AlertCircle, Printer } from 'lucide-react';
import { Asset } from '../types';
import { productionApi } from '../services/apiClient';
import { useAuth } from '../components/AuthContext';

// Utility to generate batch name
const generateBatchName = () => {
  const now = new Date();
  const yyyy = now.getFullYear();
  const mm = String(now.getMonth() + 1).padStart(2, '0');
  const dd = String(now.getDate()).padStart(2, '0');
  const hh = String(now.getHours()).padStart(2, '0');
  const min = String(now.getMinutes()).padStart(2, '0');
  return `PROD_${yyyy}${mm}${dd}_${hh}${min}`;
};

interface GridRow extends Partial<Asset> {
  [key: string]: any;
  _id: string; // Temp ID for React keys
  _rowNumber?: number; // Persistent database row number
  _version?: number; // Server optimistic-lock version
  _persisted?: boolean; // Row originated from the server, not a new local draft
  _machineSearchDraft?: boolean; // SN typed into an empty persisted row, not saved yet
  syncStatus: 'draft' | 'synced'; // New field for dual-status
  _completed?: boolean;
  _missingFields?: string[];
  _completedSteps?: string[];
}

export interface ProductionEntryTemplate {
  id: string;
  name: string;
  model?: string;
  fields: { key: string; label: string; required: boolean; fieldType?: string; enabled?: boolean; scanRequired?: boolean; section?: '组装' | '高温间测试' | '包装'; sortOrder?: number }[];
}

interface ProductionEntryProps {
  selectedTemplate?: ProductionEntryTemplate | null;
  initialQuantity?: number;
  permissions?: string[];
  scanTableId?: string;
  dispatchOrderNo?: string;
  disableAutoFillPartModels?: boolean;
  initialRows?: any[];
  onBatchCompleted?: () => void;
}

const isSnColumn = (field: { key: string; label: string; fieldType?: string }) => {
  if ('scanRequired' in field) return Boolean((field as any).scanRequired);
  if (String(field.fieldType || '').toUpperCase() === 'SN') return true;
  if (/型号|model/i.test(String(field.label || ''))) return false;
  return /sn|序列号|serial/i.test(`${field.key} ${field.label}`);
};

// Any non-SN custom column is a part/model descriptor column.  Custom columns
// are often named simply "网卡"、"主板" or "品牌" rather than ending in
// "型号"; they still need the first-row value propagation behaviour.  SN
// columns remain explicitly excluded so scanning one SN never copies it to
// other devices.
const isPartModelColumn = (field: { key: string; label: string }) =>
  !isSnColumn(field)
  && !field.label.includes('整机型号')
  && field.key.toLowerCase() !== 'model'
  // A model column generated by the “需要填型号” option belongs to the
  // current row and must never be copied from row 1 to the remaining rows.
  && !field.key.toLowerCase().endsWith('__model');

// The complete machine model is also a column-level value.  It is not a
// component model and therefore must not be affected by the optional
// “配件型号不自动生成” switch.
const isMachineModelColumn = (field: { key: string; label: string }) =>
  field.key.toLowerCase() === 'model' || /整机\s*型号|整机型号/i.test(field.label);

const snOperatorGroup = (fields: { key: string; label: string }[], index: number) => {
  for (let cursor = index - 1; cursor >= 0; cursor -= 1) {
    if (isPartModelColumn(fields[cursor])) return `model:${fields[cursor].key}`;
  }
  return `sn:${fields[index].key}`;
};

const isLastSnInOperatorGroup = (fields: { key: string; label: string }[], index: number) => {
  if (!isSnColumn(fields[index])) return false;
  const group = snOperatorGroup(fields, index);
  return !fields.slice(index + 1).some((field, offset) =>
    isSnColumn(field) && snOperatorGroup(fields, index + offset + 1) === group
  );
};
const isMachineSnField = (field: { key: string; label: string }) => field.key === 'machine_sn' || /整机\s*SN|整机序列号/i.test(field.label);

const TemplateGrid: React.FC<{
  rows: GridRow[];
  template: ProductionEntryTemplate;
  onChange: (id: string, field: string, value: string) => void;
  onKeyDown: (e: React.KeyboardEvent<HTMLInputElement>, id: string, field?: string) => void;
  onDelete: (id: string) => void;
  onAddColumn: (afterKey: string) => void;
  onDeleteColumn: (fieldKey: string, fieldLabel: string) => void;
  onComplete: (id: string) => void;
  onCompleteSection: (section: string, fieldKeys: string[]) => void;
  canAddColumn: boolean;
  canDeleteColumn: boolean;
  canForceComplete: boolean;
  onBlur: (id: string, field: string, value: string) => void;
  onScanRequired: (id: string, field: string) => void;
  onStepToggle: (id: string, field: string, completed: boolean) => void;
  dispatchOrderNo?: string;
}> = ({ rows, template, onChange, onKeyDown, onDelete, onAddColumn, onDeleteColumn, onComplete, onCompleteSection, canAddColumn, canDeleteColumn, canForceComplete, onBlur, onScanRequired, onStepToggle, dispatchOrderNo }) => {
  const sectionOrder = ['组装', '高温间测试', '包装'] as const;
  const groups = sectionOrder.map(section => ({ section, fields: template.fields.map((field, fieldIndex) => ({ field, fieldIndex })).filter(({ field }) => (field.section || '组装') === section).sort((a, b) => Number(a.field.sortOrder ?? a.fieldIndex) - Number(b.field.sortOrder ?? b.fieldIndex)) })).filter(group => group.fields.length > 0);
  const [activeSection, setActiveSection] = React.useState<string | null>(null);
  const unfinishedGroups = groups.filter(group => !(rows.length > 0 && rows.every(row => group.fields.map(({ field }) => field.key).every(key => row._completedSteps?.includes(key)))));
  return (
  <div className="w-full overflow-x-auto pb-4">
    {!activeSection && <div className="mb-5 grid gap-4 md:grid-cols-3">
      {groups.map(group => { const fieldKeys = group.fields.map(({ field }) => field.key); const sectionDone = rows.length > 0 && rows.every(row => fieldKeys.every(key => row._completedSteps?.includes(key))); return <button type="button" key={group.section} disabled={sectionDone} onClick={() => setActiveSection(group.section)} className={`rounded-2xl border p-5 text-left shadow-sm transition ${sectionDone ? 'cursor-not-allowed border-emerald-200 bg-emerald-50 opacity-60' : 'border-cyan-200 bg-white hover:-translate-y-0.5 hover:border-cyan-500 hover:shadow-md'}`}><div className="flex items-center justify-between"><span className="text-base font-bold text-cyan-900">{group.section}</span><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${sectionDone ? 'bg-emerald-100 text-emerald-700' : 'bg-cyan-100 text-cyan-700'}`}>{sectionDone ? '已完成' : '待处理'}</span></div><p className="mt-3 text-sm text-slate-600">{group.fields.length} 个具体流程</p><p className="mt-1 text-xs text-slate-400">{sectionDone ? '该区域已完工并自动隐藏' : '点击进入流程明细与扫码录入 →'}</p></button>; })}
    </div>}
    {activeSection && <div className="mb-4 flex items-center justify-between rounded-xl border border-cyan-200 bg-cyan-50 px-4 py-3"><div><p className="text-xs font-semibold text-cyan-700">当前设备流程</p><h3 className="text-base font-bold text-cyan-900">{activeSection}</h3></div><button type="button" onClick={() => setActiveSection(null)} className="rounded-lg border border-cyan-300 bg-white px-3 py-1.5 text-sm font-semibold text-cyan-800 hover:bg-cyan-100">返回三大流程</button></div>}
    {(activeSection ? groups.filter(group => group.section === activeSection) : unfinishedGroups.filter(group => false)).map(group => { const fieldKeys = group.fields.map(({ field }) => field.key); const sectionDone = rows.length > 0 && rows.every(row => fieldKeys.every(key => row._completedSteps?.includes(key))); return <section key={group.section} className="mb-5 overflow-visible rounded-xl border border-cyan-200 bg-white shadow-sm"><div className="border-b border-cyan-100 bg-cyan-50 px-4 py-3"><h3 className="text-sm font-bold tracking-wide text-cyan-900">{group.section}</h3><p className="mt-0.5 text-xs text-cyan-700">{group.fields.length} 个细化流程 · {sectionDone ? '流程已全部完成，请手动点击设备完工' : '进行中'}</p></div><table className="w-max min-w-full divide-y divide-gray-200">
      <thead className="bg-cyan-50">
        <tr>
          <th className="z-10 bg-cyan-50 px-3 py-3 text-center text-xs font-bold text-slate-600">序号</th>
          <th className="whitespace-nowrap px-3 py-3 text-left text-xs font-bold text-slate-600">派工单号</th>
          {group.fields.map(({ field, fieldIndex }) => (
            <React.Fragment key={field.key}>
              <th style={isMachineSnField(field) ? { position: 'sticky', left: 0, zIndex: 30, minWidth: 150 } : undefined} className={`whitespace-nowrap px-3 py-3 text-left text-xs font-bold text-slate-600 ${isMachineSnField(field) ? 'bg-cyan-50 shadow-[2px_0_4px_rgba(15,23,42,.12)]' : ''}`}>
                <span className="inline-flex items-center gap-1.5">{field.label}{field.required && <span className="text-red-500"> *</span>}<button disabled={!canAddColumn} onClick={() => onAddColumn(field.key)} className={`grid h-5 w-5 place-items-center rounded-full text-sm font-bold leading-none text-white ${canAddColumn ? 'bg-cyan-700 hover:bg-cyan-800' : 'cursor-not-allowed bg-slate-300'}`} title={canAddColumn ? `在${field.label}右侧添加列` : '当前账号没有生产录入新增列权限'}>+</button><button disabled={!canDeleteColumn} onClick={() => onDeleteColumn(field.key, field.label)} className={`grid h-5 w-5 place-items-center rounded-full text-sm font-bold leading-none text-white ${canDeleteColumn ? 'bg-red-600 hover:bg-red-700' : 'cursor-not-allowed bg-slate-300'}`} title={canDeleteColumn ? `删除${field.label}列` : '当前账号没有删除扫码表列权限'}>−</button></span>
              </th>
              {isSnColumn(field) && <th className="whitespace-nowrap px-3 py-3 text-left text-xs font-bold text-cyan-700">操作员</th>}
            </React.Fragment>
          ))}
          <th className="px-3 py-3 text-center text-xs font-bold text-slate-600">操作</th>
        </tr>
      </thead>
      <tbody className="divide-y divide-gray-200 bg-white">
        {rows.filter(row => !row._completed).map((row, index) => (
          <tr key={row._id} className="hover:bg-cyan-50/30">
            <td className="bg-white px-3 py-2 text-center text-xs text-slate-400">{index + 1}</td>
            <td className="whitespace-nowrap px-3 py-2 text-sm font-semibold text-slate-700">{dispatchOrderNo || '—'}</td>
            {group.fields.map(({ field, fieldIndex }) => {
              const value = String(row[field.key] || '');
              // Keep one visible operator column beside every SN field. This
              // avoids hiding the power-SN operator when a template inserts a
              // model/custom field between two component groups.
              const showOperator = isSnColumn(field);
              const operatorGroup = snOperatorGroup(template.fields, fieldIndex);
              const groupOperator = showOperator
                ? template.fields
                    .map((candidate, candidateIndex) => ({ candidate, candidateIndex }))
                    .filter(({ candidate, candidateIndex }) => isSnColumn(candidate) && snOperatorGroup(template.fields, candidateIndex) === operatorGroup)
                    .map(({ candidate }) => row[`${candidate.key}_operator`])
                    .find(Boolean)
                : '';
              const displayedOperator = row[`${field.key}_operator`] || groupOperator;
              return <React.Fragment key={field.key}>
                <td style={isMachineSnField(field) ? { position: 'sticky', left: 0, zIndex: 25, minWidth: 150 } : undefined} className={`min-w-[150px] p-1 ${isMachineSnField(field) ? 'bg-white shadow-[2px_0_4px_rgba(15,23,42,.12)]' : ''}`}>
                  {field.enabled !== false && <label className="mb-0.5 flex items-center gap-1 px-2 text-[10px] text-slate-500"><input type="checkbox" checked={row._completedSteps?.includes(field.key) || false} onChange={event => onStepToggle(row._id, field.key, event.target.checked)} />流程完成</label>}
                  <input data-field={field.key} data-label={field.label} readOnly={Boolean(row._completed)} className={`scanner-input w-full rounded border-0 border-b-2 px-2 py-1.5 text-sm focus:border-cyan-600 focus:bg-white focus:ring-0 ${row._missingFields?.includes(field.key) ? 'border-red-500 bg-red-50 text-red-800 ring-2 ring-red-200' : 'border-transparent bg-transparent'} ${row._completed ? 'cursor-not-allowed bg-slate-50 font-semibold text-slate-600' : ''}`} value={value} placeholder={row._missingFields?.includes(field.key) ? `${field.label}未录入` : field.label} onFocus={() => field.scanRequired && onScanRequired(row._id, field.key)} onKeyDown={e => onKeyDown(e, row._id, field.key)} onBlur={e => onBlur(row._id, field.key, e.target.value)} onChange={e => onChange(row._id, field.key, e.target.value)} />
                </td>
                {showOperator && <td className="min-w-[120px] bg-cyan-50/40 px-2 py-2 text-xs text-cyan-800">{displayedOperator || '—'}</td>}
              </React.Fragment>;
            })}
            <td className="whitespace-nowrap px-3 py-2 text-center">
              <button onClick={() => onComplete(row._id)} className={`rounded px-3 py-1.5 text-xs font-semibold text-white ${row._missingFields?.length ? (canForceComplete ? 'bg-amber-600 hover:bg-amber-700' : 'bg-red-500 hover:bg-red-600') : 'bg-emerald-600 hover:bg-emerald-700'}`}>{row._missingFields?.length ? (canForceComplete ? '强制完工' : '补齐后完工') : '完工'}</button>
              <button onClick={() => onDelete(row._id)} className="ml-2 text-xs text-red-500 hover:underline">删除</button>
            </td>
          </tr>
        ))}
      </tbody>
    </table></section>; })}
    {!activeSection && unfinishedGroups.length === 0 && <div className="rounded-xl border border-dashed border-emerald-300 bg-emerald-50 px-6 py-10 text-center text-sm font-semibold text-emerald-700">该设备的组装、高温间测试、包装流程均已完成。</div>}
    {rows.length > 0 && rows.every(row => row._completed) && <div className="border-t border-emerald-100 bg-emerald-50 px-6 py-10 text-center text-sm font-semibold text-emerald-700">本批次设备已全部完工，待扫码列表已清零。</div>}
  </div>
  );
};

const ProductionEntry: React.FC<ProductionEntryProps> = ({ selectedTemplate, initialQuantity, permissions, scanTableId, initialRows, dispatchOrderNo, disableAutoFillPartModels = false, onBatchCompleted }) => {
  const { user } = useAuth();
  const effectivePermissions = permissions || user?.permissions || [];
  const hasPermission = (code: string) => effectivePermissions.includes(code) || effectivePermissions.includes(`PERM_${code}`);
  const canAddColumn = hasPermission('ADD_PRODUCTION_COLUMN');
  const canDeleteColumn = effectivePermissions.includes('DELETE_PRODUCTION_COLUMN');
  const canForceDuplicate = hasPermission('FORCE_DUPLICATE_SN');
  const canForceComplete = hasPermission('FORCE_COMPLETE_SCAN');
  const canDeleteRow = hasPermission('CREATE_SCAN_TABLE') || hasPermission('MANAGE_PRODUCTION') || hasPermission('OPERATE_SCAN');
  const operatorNo = user ? `${user.username}${user.id ? ` (#${user.id})` : ''}` : '未登录';
  // Keep optimistic-lock versions outside React's asynchronous render cycle.
  // Blur events can arrive back-to-back while a previous request is still in
  // flight; the ref lets the save queue always use the server's latest version.
  const rowVersionsRef = useRef<Record<string, number>>({});
  const rowSaveQueuesRef = useRef<Record<string, Promise<unknown>>>({});
  // -- State --
  const [batchName, setBatchName] = useState(generateBatchName());
  const [rows, setRows] = useState<GridRow[]>([
    { _id: '1', contract_no: '', model: '', machine_sn: '', syncStatus: 'draft' }
  ]);
  useEffect(() => {
    if (!initialRows?.length || !selectedTemplate) return;
    const mappedRows = initialRows.map((source:any, index:number) => {
      // The backend is authoritative. Keep every persisted field key (including
      // custom keys such as field14_2) instead of reducing rows to Asset fields.
      const values = Object.fromEntries((source.values || []).flatMap((item:any) => {
        const key = item.fieldKey || item.field_key;
        const value = item.value ?? item.fieldValue ?? item.field_value ?? '';
        const operator = item.operatorNo || item.operator_no || '';
        return operator ? [[key, value], [`${key}_operator`, operator]] : [[key, value]];
      }));
      const modelField = (selectedTemplate.fields || []).find((field:any) =>
        !String(field.key).toLowerCase().includes('sn') &&
        /型号|model/i.test(String(field.label || field.key))
      );
      const machineField = (selectedTemplate.fields || []).find((field:any) => isMachineSnField({ key: String(field.key || ''), label: String(field.label || field.key || '') }));
      const modelValue = modelField ? values[modelField.key] : undefined;
      const mapped: GridRow = {
        _id: String(source.id || index + 1),
        _rowNumber: Number(source.rowNumber || source.row_number || index + 1),
        _version: Number(source.version ?? 0),
        _persisted: true,
        ...values,
        // Keep compatibility with older API payloads that did not expose
        // row.machineSn: resolve the value from the template's actual
        // “整机 SN” field as a fallback.
        machine_sn: source.machineSn || values.machine_sn || (machineField ? values[machineField.key] : '') || '',
        model: modelValue || values.model || selectedTemplate.model || '',
        syncStatus: source.status === 'COMPLETED' ? 'synced' : 'draft',
        _completed: source.status === 'COMPLETED',
        _completedSteps: Array.isArray(source.completedSteps) ? source.completedSteps : [],
      };
      rowVersionsRef.current[mapped._id] = mapped._version || 0;
      return mapped;
    });
    setRows(mappedRows);
    if (scanTableId) productionApi.scanProcessSteps(Number(scanTableId)).then(steps => setRows(previous => previous.map(row => ({ ...row, _completedSteps: steps[String(row._rowNumber || 0)] || [] })))).catch(() => undefined);
  }, [initialRows, selectedTemplate, scanTableId]);
  const [activeTab, setActiveTab] = useState<'scan' | 'import'>('scan');
  
  // UX State
  const [statusMsg, setStatusMsg] = useState<{ type: 'success' | 'error' | 'info', text: string } | null>(null);
  const [columnDialog, setColumnDialog] = useState<{ afterIndex: number; label: string; count: string } | null>(null);
  const [soundEnabled, setSoundEnabled] = useState(true);
  const [lastScanStatus, setLastScanStatus] = useState<'success' | 'error' | 'neutral'>('neutral');
  const [isSyncing, setIsSyncing] = useState(false);
  const [remoteAssets, setRemoteAssets] = useState<any[]>([]);
  const [lastSavedTime, setLastSavedTime] = useState<string>('');
  const [labelToPrint, setLabelToPrint] = useState<GridRow | null>(null);
  const [scanDialog, setScanDialog] = useState<{ id: string; field: string; value: string } | null>(null);
  // Each scan-table session starts with the expected production flow:
  // machine SN -> next SN column. Do not inherit another operator's browser
  // preference from localStorage; the operator may still switch the mode for
  // the current session using the controls above the grid.
  const [scanJumpMode, setScanJumpMode] = useState<'horizontal' | 'vertical'>('horizontal');

  // Network State
  const [isOnline, setIsOnline] = useState(navigator.onLine);

  const audioContextRef = useRef<AudioContext | null>(null);
  const [machineSearch, setMachineSearch] = useState('');
  const [machineSearchCompleted, setMachineSearchCompleted] = useState(false);
  const [showBatchSettings, setShowBatchSettings] = useState(false);
  const draftBatchIdRef = useRef<number | null>(null);
  const draftBatchPromiseRef = useRef<Promise<number> | null>(null);
  const [runtimeFields, setRuntimeFields] = useState(selectedTemplate?.fields || []);
  const machineValueForRow = (row: GridRow) => {
    const direct = String(row.machine_sn || '').trim();
    if (direct) return direct;
    const field = runtimeFields.find(item => isMachineSnField({ key: item.key, label: item.label }));
    return field ? String(row[field.key] || '').trim() : '';
  };
  const handleMachineSearchChange = (rawValue: string) => {
    const value = rawValue.trimStart();
    const previousSearch = machineSearch.trim();
    setMachineSearch(value);
    setMachineSearchCompleted(false);
    if (!value) return;
    // The search box is also the first-entry point for a new machine SN. If
    // there is no persisted row matching the value, bind the typed value to
    // the first empty row (or the row previously being edited) instead of
    // treating it as a failed lookup.
    setRows(previous => {
      const normalized = value.trim().toLowerCase();
      // While an operator is typing an existing SN, keep the persisted row
      // as the lookup result. Only create a new row after we know that no
      // existing machine SN contains the current input.
      if (previous.some(row => machineValueForRow(row).toLowerCase().includes(normalized))) return previous;
      const target = previous.find(row => !machineValueForRow(row) || machineValueForRow(row) === previousSearch);
      if (!target) return previous;
      return previous.map(row => row._id === target._id ? { ...row, machine_sn: value, _machineSearchDraft: true, syncStatus: row.syncStatus === 'synced' ? 'draft' : row.syncStatus } : row);
    });
  };
  const commitMachineSearch = async () => {
    const value = machineSearch.trim();
    if (!value || !scanTableId) return;
    let row: GridRow | undefined;
    let persistedLookup = false;
    // Ask the backend for the exact row first. This avoids relying on a
    // potentially stale parent snapshot and supports templates whose machine
    // SN field is not literally named machine_sn.
    try {
      const remoteRow = await productionApi.scanTableMachineRow(Number(scanTableId), value);
      const remoteValues = Object.fromEntries((remoteRow?.values || []).map((entry:any) => [entry.fieldKey || entry.field_key, entry.value ?? entry.fieldValue ?? '']));
      const rowNumber = Number(remoteRow.rowNumber || remoteRow.row_number);
      if (String(remoteRow.status || '').toUpperCase() === 'COMPLETED' || remoteRow._completed) {
        setMachineSearchCompleted(true);
        setStatusMsg({ type: 'info', text: `整机 SN ${value} 已完工，禁止再次生成或录入重复扫码表。` });
        return;
      }
      const existing = rows.find(item => Number(item._rowNumber) === rowNumber);
      const hydrated = { ...(existing || { _id: String(remoteRow.id || rowNumber) }), _rowNumber: rowNumber, _version: Number(remoteRow.version ?? existing?._version ?? 0), _persisted: true, ...remoteValues, machine_sn: remoteRow.machineSn || remoteRow.machine_sn || remoteValues.machine_sn || value, syncStatus: remoteRow.status === 'COMPLETED' ? 'synced' : 'draft' } as GridRow;
      row = hydrated;
      persistedLookup = true;
      setRows(previous => previous.some(item => Number(item._rowNumber) === rowNumber) ? previous.map(item => Number(item._rowNumber) === rowNumber ? hydrated : item) : [...previous, hydrated]);
      rowVersionsRef.current[hydrated._id] = hydrated._version || 0;
    } catch {
      row = rows.find(item => machineValueForRow(item).toLowerCase() === value.toLowerCase());
      // A local exact match is still a lookup of an existing persisted row.
      // Never write it back merely because the dedicated endpoint was
      // unavailable (for example during a brief refresh or older deployment).
      if (row?._persisted && !row._machineSearchDraft) persistedLookup = true;
    }
    // Reload the authoritative table on commit. The parent page can hold a
    // snapshot from before another operator saved the SN, so local filtering
    // alone may miss a valid persisted row.
    if (!row) {
      try {
        const remote = await productionApi.scanTable(Number(scanTableId));
        const remoteRow = (remote?.rows || []).find((candidate:any) => {
          const candidateMachine = String(candidate.machineSn || candidate.machine_sn || '').trim();
          const values = candidate.values || [];
          return candidateMachine.toLowerCase() === value.toLowerCase() || values.some((entry:any) => String(entry.value ?? entry.fieldValue ?? '').trim().toLowerCase() === value.toLowerCase());
        });
        if (remoteRow) {
          if (String(remoteRow.status || '').toUpperCase() === 'COMPLETED') {
            setMachineSearchCompleted(true);
            setStatusMsg({ type: 'info', text: `整机 SN ${value} 已完工，禁止再次生成或录入重复扫码表。` });
            return;
          }
          const remoteValues = Object.fromEntries((remoteRow.values || []).map((entry:any) => [entry.fieldKey || entry.field_key, entry.value ?? entry.fieldValue ?? '']));
          const rowNumber = Number(remoteRow.rowNumber || remoteRow.row_number);
          const existing = rows.find(item => Number(item._rowNumber) === rowNumber);
          const hydrated = { ...(existing || { _id: String(remoteRow.id || rowNumber) }), _rowNumber: rowNumber, _version: Number(remoteRow.version ?? existing?._version ?? 0), _persisted: true, ...remoteValues, machine_sn: remoteRow.machineSn || remoteRow.machine_sn || remoteValues.machine_sn || value, syncStatus: remoteRow.status === 'COMPLETED' ? 'synced' : 'draft' } as GridRow;
          row = hydrated;
          persistedLookup = true;
          setRows(previous => previous.some(item => Number(item._rowNumber) === rowNumber) ? previous.map(item => Number(item._rowNumber) === rowNumber ? hydrated : item) : [...previous, hydrated]);
          rowVersionsRef.current[hydrated._id] = hydrated._version || 0;
        }
      } catch (error:any) {
        // A completed/legacy table is intentionally rejected by the normal
        // table endpoint. Fall back to the all-table read model so a valid
        // machine SN can still be located without changing its data.
        try {
          const allTables = await productionApi.scanTablesAll();
          const remote = (allTables || []).find((candidate:any) => Number(candidate.id) === Number(scanTableId));
          const remoteRow = (remote?.rows || []).find((candidate:any) => {
            const candidateMachine = String(candidate.machineSn || candidate.machine_sn || '').trim();
            return candidateMachine.toLowerCase() === value.toLowerCase() || (candidate.values || []).some((entry:any) => String(entry.value ?? entry.fieldValue ?? '').trim().toLowerCase() === value.toLowerCase());
          });
          if (remoteRow) {
            if (String(remoteRow.status || '').toUpperCase() === 'COMPLETED') {
              setMachineSearchCompleted(true);
              setStatusMsg({ type: 'info', text: `整机 SN ${value} 已完工，禁止再次生成或录入重复扫码表。` });
              return;
            }
            const remoteValues = Object.fromEntries((remoteRow.values || []).map((entry:any) => [entry.fieldKey || entry.field_key, entry.value ?? entry.fieldValue ?? '']));
            const rowNumber = Number(remoteRow.rowNumber || remoteRow.row_number);
            const existing = rows.find(item => Number(item._rowNumber) === rowNumber);
            const hydrated = { ...(existing || { _id: String(remoteRow.id || rowNumber) }), _rowNumber: rowNumber, _version: Number(remoteRow.version ?? existing?._version ?? 0), _persisted: true, ...remoteValues, machine_sn: remoteRow.machineSn || remoteRow.machine_sn || remoteValues.machine_sn || value, syncStatus: remoteRow.status === 'COMPLETED' ? 'synced' : 'draft' } as GridRow;
            row = hydrated;
            persistedLookup = true;
            setRows(previous => previous.some(item => Number(item._rowNumber) === rowNumber) ? previous.map(item => Number(item._rowNumber) === rowNumber ? hydrated : item) : [...previous, hydrated]);
            rowVersionsRef.current[hydrated._id] = hydrated._version || 0;
          }
        } catch (fallbackError:any) {
          setStatusMsg({ type: 'error', text: fallbackError?.message || error?.message || '刷新扫码表数据失败，请重试。' });
        }
      }
    }
    if (!row || !row._rowNumber) return;
    // Looking up an existing row must be read-only. Saving the same SN here
    // would incorrectly replace the original scan operator with the account
    // performing the lookup.
    if (persistedLookup) {
      setStatusMsg({ type: 'info', text: `已定位整机 SN ${value}，未修改原扫码数据。` });
      return;
    }
    try {
      const saved = await productionApi.saveScanRow(Number(scanTableId), row._rowNumber, [{ fieldKey: 'machine_sn', value }], rowVersionsRef.current[row._id]);
      const persistedRow = (saved?.rows || []).find((item:any) => Number(item.rowNumber || item.row_number) === Number(row._rowNumber));
      rowVersionsRef.current[row._id] = Number(persistedRow?.version ?? saved?.version ?? rowVersionsRef.current[row._id] ?? 0);
      const machineValue = (persistedRow?.values || []).find((item:any) => String(item.fieldKey || item.field_key) === 'machine_sn');
      const machineOperator = machineValue?.operatorNo || machineValue?.operator_no || '';
      setRows(previous => previous.map(item => item._id === row?._id ? { ...item, _persisted: true, _machineSearchDraft: false, machine_sn: value, machine_sn_operator: machineOperator, syncStatus: 'synced' } : item));
      setStatusMsg({ type: 'success', text: `整机 SN ${value} 已保存，可以继续录入配件。` });
    } catch (error:any) {
      setStatusMsg({ type: 'error', text: error?.message || '整机 SN 保存失败，请重试。' });
    }
  };
  // Also resolve completed/partially scanned rows while the operator is
  // typing (without requiring blur or Enter). The exact-match endpoint is
  // deliberately used only after a reasonable SN length to avoid noisy
  // requests for every short prefix.
  useEffect(() => {
    const value = machineSearch.trim();
    if (!scanTableId || value.length < 6) return;
    const timer = window.setTimeout(async () => {
      try {
        const remoteRow = await productionApi.scanTableMachineRow(Number(scanTableId), value);
        const remoteValue = String(remoteRow?.machineSn || remoteRow?.machine_sn || '').trim();
        if (!remoteValue || remoteValue.toLowerCase() !== value.toLowerCase()) return;
        if (String(remoteRow.status || '').toUpperCase() === 'COMPLETED' || remoteRow._completed) {
          setMachineSearchCompleted(true);
          setStatusMsg({ type: 'info', text: `整机 SN ${value} 已完工，禁止再次生成或录入重复扫码表。` });
          return;
        }
        const remoteValues = Object.fromEntries((remoteRow.values || []).map((entry:any) => [entry.fieldKey || entry.field_key, entry.value ?? entry.fieldValue ?? '']));
        const rowNumber = Number(remoteRow.rowNumber || remoteRow.row_number);
        setRows(previous => {
          const existing = previous.find(item => Number(item._rowNumber) === rowNumber);
          const hydrated = { ...(existing || { _id: String(remoteRow.id || rowNumber) }), _rowNumber: rowNumber, _version: Number(remoteRow.version ?? existing?._version ?? 0), _persisted: true, ...remoteValues, machine_sn: remoteValue, syncStatus: remoteRow.status === 'COMPLETED' ? 'synced' : 'draft' } as GridRow;
          rowVersionsRef.current[hydrated._id] = hydrated._version || 0;
          return previous.some(item => Number(item._rowNumber) === rowNumber) ? previous.map(item => Number(item._rowNumber) === rowNumber ? hydrated : item) : [...previous, hydrated];
        });
      } catch { /* prefix is incomplete or row is not in this table yet */ }
    }, 250);
    return () => window.clearTimeout(timer);
  }, [machineSearch, scanTableId]);
  const ensureDraftBatch = useCallback(async () => {
    if (draftBatchIdRef.current) return draftBatchIdRef.current;
    if (!draftBatchPromiseRef.current) {
      draftBatchPromiseRef.current = productionApi.createBatch(batchName)
        .then((batch: any) => {
          draftBatchIdRef.current = Number(batch.id);
          return Number(batch.id);
        })
        .finally(() => { draftBatchPromiseRef.current = null; });
    }
    return draftBatchPromiseRef.current;
  }, [batchName]);

  const persistDraftRow = useCallback(async (row: GridRow) => {
    // A persisted scan table owns its rows. Never replay those machine SNs
    // into the legacy production-batch draft API when merely opening it.
    if (scanTableId || !selectedTemplate || !row.machine_sn) return;
    const batchId = await ensureDraftBatch();
    await productionApi.saveDraftRow(batchId, {
      machineSn: row.machine_sn,
      model: row.model,
      contractNo: row.contract_no,
      ...(row.invoice_date ? { invoiceDate: row.invoice_date } : {}),
    });
    const componentRows = runtimeFields
      .filter(field => field.key.toLowerCase().includes('sn') && field.key !== 'machine_sn')
      .map(field => {
        const modelAliases: Record<string, string> = {
          cpu_sn: 'cpu_model',
          cpu_sn_2: 'cpu_model',
          mem_sns: 'mem_info',
          hdd_sn: 'hdd_info',
          psu_cage_sn: 'psu_info',
          psu_module_1_sn: 'psu_info',
          psu_module_2_sn: 'psu_info',
        };
        const modelKey = modelAliases[field.key] || field.key.replace(/_?sns?$/i, '_model');
        return {
          type: field.label.replace(/SN/ig, '').trim() || field.key,
          model: row[modelKey] || '',
          serialNo: row[field.key] || '',
        };
      });
    await productionApi.saveDraftComponents(batchId, row.machine_sn as string, componentRows);
    setLastSavedTime(new Date().toLocaleTimeString());
  }, [ensureDraftBatch, runtimeFields, selectedTemplate, scanTableId]);

  useEffect(() => {
    if (selectedTemplate) setRuntimeFields(selectedTemplate.fields.map(field => ({ ...field })));
  }, [selectedTemplate]);

  // When MES confirms a template and quantity, create the requested number of
  // draft rows. Existing rows are intentionally replaced only by this explicit
  // confirmation action (never while the operator is merely browsing templates).
  useEffect(() => {
    if (!selectedTemplate || !initialQuantity || initialQuantity < 1) return;
    // A persisted scan table row from the server must win over browser drafts.
    if (initialRows?.length) return;
    const quantity = Math.min(Math.floor(initialQuantity), 5000);
    const keyMap: Record<string, keyof Asset> = {
      machineSn: 'machine_sn', machine_sn: 'machine_sn',
      model: 'model', contractNo: 'contract_no', contract_no: 'contract_no', mbModel: 'mb_model', mb_model: 'mb_model', mbSn: 'mb_sn', mb_sn: 'mb_sn', cpuModel: 'cpu_model', cpu_model: 'cpu_model', cpuSn: 'cpu_sn', cpu_sn: 'cpu_sn', memModel: 'mem_info', mem_info: 'mem_info', memSn: 'mem_sns', mem_sns: 'mem_sns', hddModel: 'hdd_info', hdd_info: 'hdd_info', hddSn: 'hdd_sn', hdd_sn: 'hdd_sn', psuModel: 'psu_info', psu_info: 'psu_info', psuSn: 'psu_cage_sn', psu_cage_sn: 'psu_cage_sn',
    };
    const generated: GridRow[] = Array.from({ length: quantity }, (_, index) => {
      const templateModel = selectedTemplate.model || selectedTemplate.name;
      const row: GridRow = { _id: `${Date.now()}-${index}`, model: templateModel, syncStatus: 'draft' };
      selectedTemplate.fields.forEach(field => {
        const key = keyMap[field.key];
        if (key === 'model' || field.label.includes('整机型号')) row[field.key] = templateModel;
        else if (key) row[key] = '';
      });
      return row;
    });
    setRows(generated);
    setBatchName(`${selectedTemplate.name}_${generateBatchName()}`);
    setStatusMsg(null);
    setActiveTab('scan');
  }, [selectedTemplate, initialQuantity]);

  // Persist every scanned machine row shortly after its SN changes. The
  // server keeps the batch in DRAFT so multiple operators can see the latest
  // row without prematurely committing the batch.
  useEffect(() => {
    if (scanTableId || !selectedTemplate) return;
    const draftRows = rows.filter(row => row.machine_sn && !row._completed);
    if (!draftRows.length) return;
    const timer = window.setTimeout(async () => {
      try {
        await Promise.all(draftRows.map(persistDraftRow));
        setLastSavedTime(new Date().toLocaleTimeString());
        setStatusMsg({ type: 'success', text: '扫码数据已自动保存并同步到服务器。' });
      } catch (error: any) {
        setStatusMsg({ type: 'error', text: error?.message || '扫码数据服务器同步失败，请稍后重试。' });
      }
    }, 800);
    return () => window.clearTimeout(timer);
  }, [rows, selectedTemplate, persistDraftRow, scanTableId]);

  // -- Network Listener --
  useEffect(() => {
    const handleOnline = () => setIsOnline(true);
    const handleOffline = () => setIsOnline(false);
    window.addEventListener('online', handleOnline);
    window.addEventListener('offline', handleOffline);
    return () => {
      window.removeEventListener('online', handleOnline);
      window.removeEventListener('offline', handleOffline);
    };
  }, []);

  useEffect(() => {
    productionApi.listAssets().then(setRemoteAssets).catch(() => undefined);
  }, []);

  // Cleanup
  useEffect(() => {
    return () => {
      if (audioContextRef.current) audioContextRef.current.close();
    };
  }, []);

  // -- Audio Feedback --
  const playFeedbackSound = (type: 'success' | 'error') => {
    if (!soundEnabled) return;
    try {
      if (!audioContextRef.current) {
        audioContextRef.current = new (window.AudioContext || (window as any).webkitAudioContext)();
      }
      const ctx = audioContextRef.current;
      if (ctx.state === 'suspended') ctx.resume();

      const oscillator = ctx.createOscillator();
      const gainNode = ctx.createGain();

      oscillator.connect(gainNode);
      gainNode.connect(ctx.destination);

      if (type === 'success') {
        oscillator.type = 'sine';
        oscillator.frequency.setValueAtTime(1000, ctx.currentTime);
        oscillator.frequency.exponentialRampToValueAtTime(1200, ctx.currentTime + 0.1);
        gainNode.gain.setValueAtTime(0.3, ctx.currentTime);
        gainNode.gain.exponentialRampToValueAtTime(0.01, ctx.currentTime + 0.15);
        oscillator.start();
        oscillator.stop(ctx.currentTime + 0.15);
      } else {
        oscillator.type = 'sawtooth';
        oscillator.frequency.setValueAtTime(200, ctx.currentTime);
        oscillator.frequency.linearRampToValueAtTime(150, ctx.currentTime + 0.3);
        gainNode.gain.setValueAtTime(0.3, ctx.currentTime);
        gainNode.gain.linearRampToValueAtTime(0.01, ctx.currentTime + 0.3);
        oscillator.start();
        oscillator.stop(ctx.currentTime + 0.3);
      }
    } catch (e) { console.warn("Audio failed", e); }
  };

  // -- Handlers --

  const handleCellChange = (id: string, field: keyof Asset, value: string) => {
    setRows(prev => prev.map(r => {
      if (r._id === id) {
        // If editing a synced row, revert it to draft
        const newStatus = r.syncStatus === 'synced' ? 'draft' : r.syncStatus;
        const next: GridRow = { ...r, [field]: value, syncStatus: newStatus };
        const operatorFields: Record<string, string> = {
          machine_sn: 'machine_sn_operator', mb_sn: 'mb_sn_operator',
          cpu_sn: 'cpu_sn_operator', cpu_sn_2: 'cpu_sn_2_operator',
          psu_cage_sn: 'psu_cage_sn_operator', psu_module_1_sn: 'psu_module_1_sn_operator',
          psu_module_2_sn: 'psu_module_2_sn_operator', hdd_sn: 'hdd_sn_operator',
          mem_sns: 'mem_sns_operator', pcie_sn: 'pcie_sn_operator'
        };
        const metadata = runtimeFields.find(item => item.key === String(field));
        const isSnField = /sn|序列号/i.test(`${String(field)} ${metadata?.label || ''}`);
        const operatorKey = operatorFields[String(field)] || (isSnField ? `${String(field)}_operator` : '');
        if (operatorKey) next[operatorKey] = value.trim() ? operatorNo : '';
        return next;
      }
      return r;
    }));
  };

  const handleTemplateCellChange = (id: string, field: string, value: string) => {
    const metadata = runtimeFields.find(item => item.key === field);
    const isSn = /sn|序列号/i.test(`${field} ${metadata?.label || ''}`);
    const isPartModel = isPartModelColumn({ key: field, label: metadata?.label || field });
    const isMachineModel = isMachineModelColumn({ key: field, label: metadata?.label || field });
    const isFirstRow = rows[0]?._id === id;
    if ((isMachineModel || (!disableAutoFillPartModels && isPartModel)) && isFirstRow) {
      setRows(previous => previous.map(row => ({ ...row, [field]: value })));
      return;
    }
    handleCellChange(id, field as keyof Asset, value);
  };

  const handleTemplateBlur = async (id: string, field: string, value: string) => {
    const metadata = runtimeFields.find(item => item.key === field);
    const isSnField = /sn|序列号/i.test(`${field} ${metadata?.label || ''}`);
    const isPartModel = isPartModelColumn({ key: field, label: metadata?.label || field });
    const isMachineModel = isMachineModelColumn({ key: field, label: metadata?.label || field });
    if (scanTableId && Number.isFinite(Number(scanTableId))) {
      const sourceIndex = rows.findIndex(item => item._id === id);
      if (sourceIndex >= 0) {
        const saveOne = async (row: GridRow, rowIndex: number, override?: string) => {
          const rowKey = row._id;
          const run = async () => {
          const expectedVersion = rowVersionsRef.current[rowKey] ?? row._version;
          const saved = await productionApi.saveScanRow(Number(scanTableId), row._rowNumber || rowIndex + 1, [{ fieldKey: field, value: override ?? String(row[field] || '') }], expectedVersion);
          const persisted = (saved?.rows || []).find((candidate: any) => Number(candidate.rowNumber || candidate.row_number) === Number(row._rowNumber || rowIndex + 1));
          if (persisted?.version != null) {
            rowVersionsRef.current[rowKey] = Number(persisted.version);
            setRows(previous => previous.map(item => item._id === rowKey ? { ...item, _version: Number(persisted.version) } : item));
          }
          return saved;
          };
          const previous = rowSaveQueuesRef.current[rowKey] || Promise.resolve();
          const task = previous.catch(() => undefined).then(run);
          rowSaveQueuesRef.current[rowKey] = task;
          // Attach cleanup handlers without creating an unhandled rejected
          // promise when the queued request itself fails.
          void task.then(() => {
            if (rowSaveQueuesRef.current[rowKey] === task) delete rowSaveQueuesRef.current[rowKey];
          }, () => {
            if (rowSaveQueuesRef.current[rowKey] === task) delete rowSaveQueuesRef.current[rowKey];
          });
          return task;
        };
        try {
          const firstRow = sourceIndex === 0 && (isMachineModel || (!disableAutoFillPartModels && isPartModel));
          if (firstRow) {
            const propagated = String(value || '');
            // Saving in parallel makes each request carry the same row
            // version and causes false 409 conflicts during model autofill.
            // Serialize the propagation so every row uses its own fresh
            // version while preserving optimistic concurrency for real edits.
            for (const [rowIndex, row] of rows.entries()) {
              await saveOne(row, rowIndex, propagated);
            }
          } else {
            await saveOne(rows[sourceIndex], sourceIndex, value);
          }
          setStatusMsg({ type: 'success', text: `${metadata?.label || field} 已自动保存并同步。` });
        } catch (error: any) {
          setStatusMsg({ type: 'error', text: error?.message || `${metadata?.label || field} 保存失败。` });
          return;
        }
      }
    }
    if (!isSnField) return;
    if (!value.trim()) {
      setStatusMsg({ type: 'success', text: `${metadata?.label || field} 已清空并同步，可重新扫码填写。` });
      return;
    }
    if (!canForceDuplicate) {
      const local = duplicateDetails(value, id);
      if (local) { setStatusMsg({ type: 'error', text: `SN ${value} 重复：设备 ${local}` }); return; }
      try {
        const currentRowIndex = rows.findIndex(item => item._id === id);
        const currentRow = currentRowIndex >= 0 ? rows[currentRowIndex] : undefined;
        const currentRowNumber = currentRow?._rowNumber || (currentRowIndex >= 0 ? currentRowIndex + 1 : undefined);
        const found = await productionApi.duplicateSn(value, scanTableId ? Number(scanTableId) : undefined, currentRowNumber);
        if (found.machineSn) {
          setRows(previous => previous.map(row => row._id === id ? { ...row, [field]: '' } : row));
          setStatusMsg({ type: 'error', text: `SN ${value} 重复：设备 ${found.machineSn} 的 ${found.component || '整机 SN'}` });
          return;
        }
      } catch { /* the save request below provides the authoritative error */ }
    }
    const row = rows.find(item => item._id === id);
    if (!row) return;
    try {
      // Scanning a serial-number process also completes that process.  Keep
      // this as a server-side action (rather than only changing the checkbox
      // locally) so every operator sees the same completion state.
      const completed = await toggleStep(id, field, true);
      if (!completed) return;
      await persistDraftRow({ ...row, [field]: value });
      setStatusMsg({ type: 'success', text: `SN ${value} 已自动保存，生产数据查询已同步。` });
    } catch (error: any) {
      setStatusMsg({ type: 'error', text: error?.message || `SN ${value} 保存失败，请重试。` });
    }
  };

  const openScanDialog = (id: string, field: string) => {
    const row = rows.find(item => item._id === id);
    if (!row || String(row[field] || '').trim()) return;
    const metadata = runtimeFields.find(item => item.key === field);
    if (!metadata?.scanRequired) return;
    setScanDialog({ id, field, value: '' });
  };
  const confirmScanDialog = async () => {
    if (!scanDialog || !scanDialog.value.trim()) {
      setStatusMsg({ type: 'error', text: '请先录入该流程的 SN。' });
      return;
    }
    const { id, field, value } = scanDialog;
    handleTemplateCellChange(id, field, value.trim());
    setScanDialog(null);
    await handleTemplateBlur(id, field, value.trim());
  };
  const toggleStep = async (id: string, field: string, completed: boolean): Promise<boolean> => {
    const row = rows.find(item => item._id === id);
    const rowNumber = row?._rowNumber;
    if (scanTableId && rowNumber) {
      try {
        const version = rowVersionsRef.current[row._id] ?? row._version;
        const saved = await productionApi.toggleScanStep(Number(scanTableId), rowNumber, field, completed, version);
        const persisted = (saved?.rows || []).find((candidate: any) => Number(candidate.rowNumber || candidate.row_number) === Number(rowNumber));
        if (persisted?.version != null) rowVersionsRef.current[row._id] = Number(persisted.version);
        if (Array.isArray(persisted?.completedSteps)) {
          setRows(previous => previous.map(item => item._id === id ? { ...item, _completedSteps: persisted.completedSteps } : item));
        }
      }
      catch (error: any) { setStatusMsg({ type: 'error', text: error?.message || '流程状态保存失败。' }); return false; }
    }
    setRows(previous => previous.map(item => {
      if (item._id !== id) return item;
      const steps = new Set(item._completedSteps || []); completed ? steps.add(field) : steps.delete(field);
      return { ...item, _completedSteps: Array.from(steps) };
    }));
    return true;
  };

  const completeSection = async (section: string, fieldKeys: string[]) => {
    const pending = rows.filter(row => !row._completed && !fieldKeys.every(key => row._completedSteps?.includes(key)));
    try {
      if (scanTableId) {
        for (const row of pending) if (row._rowNumber) await productionApi.completeScanSection(Number(scanTableId), row._rowNumber, section, row._version);
      }
      setRows(previous => previous.map(item => ({ ...item, _completedSteps: Array.from(new Set([...(item._completedSteps || []), ...fieldKeys])) })));
      setStatusMsg({ type: 'success', text: `${section}已完工并自动隐藏，其他分区不受影响。` });
    } catch (error: any) { setStatusMsg({ type: 'error', text: error?.message || `${section}完工失败` }); }
  };

  const insertRuntimeColumn = (afterKey: string) => {
    const afterIndex = runtimeFields.findIndex(field => field.key === afterKey);
    setColumnDialog({ afterIndex: afterIndex < 0 ? runtimeFields.length - 1 : afterIndex, label: '', count: '1' });
  };
  const confirmRuntimeColumns = async () => {
    if (!columnDialog) return;
    const label = columnDialog.label.trim();
    if (!label) {
      setStatusMsg({ type: 'error', text: '请输入新增列名称。' });
      return;
    }
    const requestedCount = Number(columnDialog.count);
    if (!Number.isInteger(requestedCount) || requestedCount < 1 || requestedCount > 50) {
      setStatusMsg({ type: 'error', text: '列数量必须是 1 到 50 之间的整数。' });
      return;
    }
    const afterIndex = columnDialog.afterIndex;
    const safe = label.toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]+/g, '_');
    const type = label.toLowerCase().includes('sn') ? 'sn' : 'name';
    const stamp = Date.now();
    const section = runtimeFields[afterIndex]?.section || '组装';
    const newFields = Array.from({ length: requestedCount }, (_, index) => ({
      key: `extra_${safe}_${type}_${stamp}_${index + 1}`,
      label,
      required: false,
      enabled: true,
      scanRequired: type === 'sn',
      requireModel: false,
      section,
      sortOrder: (runtimeFields[afterIndex]?.sortOrder ?? afterIndex) + index + 1,
    }));
    try {
      // Insert sequentially so the server keeps the requested columns
      // together and preserves their order after the clicked column.
      let previousKey = runtimeFields[afterIndex]?.key || '';
      for (const field of newFields) {
        if (scanTableId) await productionApi.addScanColumn(Number(scanTableId), field.key, field.label, previousKey, section);
        previousKey = field.key;
      }
    } catch (error: any) {
      setStatusMsg({ type: 'error', text: error?.message || '新增列同步失败。' });
      return;
    }
    setColumnDialog(null);
    setRuntimeFields(fields => {
      const next = [...fields];
      next.splice(afterIndex + 1, 0, ...newFields);
      return next;
    });
    setStatusMsg({ type: 'success', text: `已添加 ${requestedCount} 列“${label}”，并同步到服务器。` });
  };
  const deleteRuntimeColumn = async (fieldKey: string, fieldLabel: string) => {
    if (!canDeleteColumn) return;
    if (fieldKey === 'model' || fieldLabel.includes('整机型号')) {
      setStatusMsg({ type: 'error', text: '整机型号为系统字段，不能删除。' });
      return;
    }
    if (!window.confirm(`确认删除“${fieldLabel}”列吗？该列已录入的数据也会一并删除。`)) return;
    try {
      if (scanTableId) await productionApi.deleteScanColumn(Number(scanTableId), fieldKey);
      setRuntimeFields(fields => fields.filter(field => field.key !== fieldKey));
      setRows(previous => previous.map(row => {
        const next = { ...row };
        delete next[fieldKey];
        delete next[`${fieldKey}_operator`];
        return next;
      }));
      setStatusMsg({ type: 'success', text: `“${fieldLabel}”列已删除并同步。` });
    } catch (error: any) {
      setStatusMsg({ type: 'error', text: error?.message || `“${fieldLabel}”列删除失败。` });
    }
  };
  const visibleRows = showBatchSettings
    ? rows
    : machineSearch.trim()
    ? (() => {
        const normalized = machineSearch.trim().toLowerCase();
        if (machineSearchCompleted) return [];
        const matched = rows.filter(row => !row._completed && machineValueForRow(row).toLowerCase().includes(normalized));
        if (matched.length) return matched;
        // A new machine SN is intentionally not present on the server yet.
        // If this flow sheet still has an empty row, show that row immediately
        // so the operator can enter the new SN instead of receiving a false
        // “未找到” result.
        const empty = rows.find(row => !row._completed && (!row._persisted || row._machineSearchDraft) && !machineValueForRow(row));
        return empty ? [{ ...empty, machine_sn: machineSearch.trim() }] : [];
      })()
    : [];

  const completeRow = async (id: string) => {
    const row = rows.find(item => item._id === id);
    if (!row || !selectedTemplate) return;
    const missing = runtimeFields.filter(field => field.enabled !== false && field.required && !String(row[field.key] || '').trim());
    if (missing.length && !canForceComplete) {
      setRows(previous => previous.map(item => item._id === id ? { ...item, _missingFields: missing.map(field => field.key) } : item));
      setStatusMsg({ type: 'error', text: `无法完工，缺少：${missing.map(field => field.label).join('、')}。请补齐标红字段后再完工。` });
      return;
    }
    if (missing.length && canForceComplete && !window.confirm(`该设备仍缺少：${missing.map(field => field.label).join('、')}。确认强制完工吗？`)) {
      setRows(previous => previous.map(item => item._id === id ? { ...item, _missingFields: missing.map(field => field.key) } : item));
      return;
    }
    const rowIndex = rows.findIndex(item => item._id === id);
    if (scanTableId && rowIndex >= 0) {
      try {
        // Persist completion on the server first. This makes the row hidden
        // for every account, not only in the current browser.
        await productionApi.completeScanRow(Number(scanTableId), row._rowNumber || rowIndex + 1, row._version);
      } catch (error: any) {
        setStatusMsg({ type: 'error', text: error?.message || '完工保存失败，请稍后重试。' });
        return;
      }
    }
    const remaining = rows.filter(item => item._id !== id && !item._completed).length;
    setRows(previous => previous.map(item => item._id === id ? { ...item, _completed: true, _missingFields: [] } : item));
    setStatusMsg({
      type: 'success',
      text: remaining === 0 ? '本批次所有设备已完工，待扫码表格已清零，可同步批次数据。' : `设备已完工并屏蔽，剩余 ${remaining} 台待扫码。`
    });
    if (remaining === 0) {
      onBatchCompleted?.();
      if (scanTableId) {
      }
    }
  };
  const checkDuplicate = (value: string, currentId: string): boolean => {
    if (!value || value.length < 4) return false;
    // 1. Check current batch
    const inCurrentBatch = rows.some(r => r._id !== currentId && Object.values(r).some(v => v === value));
    // 2. Check history
    const inHistory = remoteAssets.some(a => Object.values(a).some(v => v === value));
    return inCurrentBatch || inHistory;
  };

  const duplicateDetails = (value: string, currentId: string): string | null => {
    const normalized = value.trim().toLowerCase();
    if (!normalized) return null;
    const fieldLabels: Record<string,string> = { machine_sn:'整机 SN',mb_sn:'主板 SN',cpu_sn:'CPU1 SN',cpu_sn_2:'CPU2 SN',psu_cage_sn:'电源 SN',psu_module_1_sn:'电源模块1 SN',psu_module_2_sn:'电源模块2 SN',hdd_sn:'硬盘 SN',mem_sns:'内存 SN',pcie_sn:'PCIE SN' };
    for (const row of rows) {
      if (row._id === currentId) continue;
      for (const [key, raw] of Object.entries(row)) {
        if (!key.toLowerCase().includes('sn') || key.endsWith('_operator')) continue;
        if (String(raw || '').trim().toLowerCase() === normalized) return `设备 ${row.machine_sn || `第 ${rows.indexOf(row)+1} 行`} 的 ${fieldLabels[key] || key}`;
      }
    }
    // Do not use the periodically refreshed asset cache for the blocking
    // decision: it can contain the same row currently being edited and would
    // produce a false duplicate warning. The backend duplicate endpoint is
    // authoritative for persisted records.
    return null;
  };

  const addNewRow = (autoFocus = false) => {
    const lastRow = rows[rows.length - 1];
    const newRow: GridRow = { 
      _id: Date.now().toString(),
      contract_no: lastRow?.contract_no || '',
      invoice_date: lastRow?.invoice_date || '',
      model: lastRow?.model || '',
      machine_sn: '',
      syncStatus: 'draft'
    };
    setRows(prev => [...prev, newRow]);
  };

  const deleteRow = async (id: string) => {
    if (!canDeleteRow) {
      setStatusMsg({ type: 'error', text: '当前账号没有删除扫码行权限' });
      return;
    }
    const target = rows.find(row => row._id === id);
    if (!target) return;
    if (target._completed) {
      setStatusMsg({ type: 'error', text: '已完工设备不能删除扫码行' });
      return;
    }
    // Rows loaded from a persisted scan table must be cancelled on the server;
    // removing them only from React state makes them reappear on the next
    // refresh and was the reason the delete button appeared ineffective.
    if (scanTableId && target._rowNumber) {
      try {
        const result = await productionApi.cancelScanRow(Number(scanTableId), target._rowNumber, target._version);
        const latest = (result?.rows || []).find((row:any) => Number(row.rowNumber || row.row_number) === target._rowNumber);
        if (latest?.version != null) rowVersionsRef.current[id] = Number(latest.version);
      } catch (error:any) {
        setStatusMsg({ type: 'error', text: error?.message || '删除扫码行失败，请刷新后重试' });
        return;
      }
    }
    setRows(previous => {
      const remaining = previous.filter(row => row._id !== id);
      return remaining.length ? remaining : [{ _id: Date.now().toString(), contract_no: '', model: '', machine_sn: '', syncStatus: 'draft' }];
    });
    setStatusMsg({ type: 'success', text: '扫码行已删除并同步到服务器' });
  };

  const handlePrintLabel = (row: GridRow) => {
    if (!row.machine_sn) {
      setStatusMsg({ type: 'error', text: '无法打印：缺少 SN' });
      return;
    }
    setLabelToPrint(row);
    // Slight delay to allow DOM to render the printable area
    setTimeout(() => {
      window.print();
      // Optional: Clear label after print (or keep it, doesn't matter since it's hidden)
      // setLabelToPrint(null); 
    }, 100);
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>, id: string, field?: string) => {
    // Barcode scanners may terminate a scan with either Enter or Tab. Treat
    // both as the scan-complete event so every operator account follows the
    // same next-SN-column workflow.
    if (e.key === 'Enter' || e.key === 'Tab') {
      e.preventDefault();
      const val = e.currentTarget.value.trim();
      
      const duplicate = duplicateDetails(val, id);
      if (duplicate && !canForceDuplicate) {
        playFeedbackSound('error');
        setLastScanStatus('error');
        setTimeout(() => setLastScanStatus('neutral'), 500);
        e.currentTarget.select();
        setStatusMsg({ type: 'error', text: `SN [${val}] 重复，已存在于${duplicate}。当前账号没有强制重复使用权限。` });
        return;
      }
      if (duplicate && canForceDuplicate && !window.confirm(`SN [${val}] 已存在于${duplicate}。确认以管理员权限强制重复使用吗？`)) { e.currentTarget.select(); return; }

      if (val.length > 0) {
        playFeedbackSound('success');
        setLastScanStatus('success');
        setTimeout(() => setLastScanStatus('neutral'), 300);
      }

      const isSnField = /sn|序列号|serial/i.test(`${field || ''} ${e.currentTarget.dataset.label || ''}`);
      if (isSnField) {
        if (scanJumpMode === 'vertical') {
          const sameFieldInputs = Array.from(document.querySelectorAll<HTMLInputElement>('.scanner-input[data-field]'))
            .filter(input => input.dataset.field === field && !input.readOnly && !input.disabled);
          const currentFieldIndex = sameFieldInputs.indexOf(e.currentTarget);
          if (currentFieldIndex >= 0 && currentFieldIndex < sameFieldInputs.length - 1) {
            sameFieldInputs[currentFieldIndex + 1].focus();
          }
          return;
        }
        const currentRow = e.currentTarget.closest('tr');
        const rowSnInputs = currentRow
          ? Array.from(currentRow.querySelectorAll<HTMLInputElement>('.scanner-input[data-field]'))
              .filter(input => /sn|序列号|serial/i.test(`${input.dataset.field || ''} ${input.dataset.label || ''}`) && !input.readOnly && !input.disabled)
          : [];
        const currentSnIndex = rowSnInputs.indexOf(e.currentTarget);
        if (currentSnIndex >= 0 && currentSnIndex < rowSnInputs.length - 1) {
          rowSnInputs[currentSnIndex + 1].focus();
          return;
        }

        const nextRow = currentRow?.nextElementSibling;
        const nextRowFirstSn = nextRow
          ? Array.from(nextRow.querySelectorAll<HTMLInputElement>('.scanner-input[data-field]'))
              .find(input => /sn|序列号|serial/i.test(`${input.dataset.field || ''} ${input.dataset.label || ''}`) && !input.readOnly && !input.disabled)
          : undefined;
        if (nextRowFirstSn) nextRowFirstSn.focus();
        return;
      }

      const inputs = Array.from(document.querySelectorAll('.scanner-input'));
      const currentIndex = inputs.indexOf(e.currentTarget);
      
      if (currentIndex !== -1 && currentIndex < inputs.length - 1) {
        (inputs[currentIndex + 1] as HTMLElement).focus();
      } else {
        addNewRow();
        playFeedbackSound('success');
        setTimeout(() => {
          const newInputs = Array.from(document.querySelectorAll('.scanner-input'));
          if (newInputs.length > currentIndex + 1) {
             (newInputs[currentIndex + 1] as HTMLElement).focus();
          }
        }, 100);
      }
    }
  };

  const handleSync = async () => {
    if (!isOnline) {
      setStatusMsg({ type: 'error', text: '当前处于离线状态，无法同步数据。数据已保存至本地。' });
      return;
    }

    const draftRows = rows.filter(r => r.syncStatus === 'draft' && r.machine_sn);
    if (draftRows.length === 0) {
      setStatusMsg({ type: 'info', text: '没有需要同步的草稿数据。' });
      return;
    }

    setIsSyncing(true);

    try {
      const batch = await productionApi.createBatch(batchName) as { id: number };
      const committedRows = draftRows.map(r => ({
        machineSn: r.machine_sn,
        contractNo: r.contract_no || undefined,
        model: r.model || undefined,
        invoiceDate: r.invoice_date || undefined
      }));
      await productionApi.commitBatch(batch.id, committedRows);
      setRows(prev => prev.map(r => r.syncStatus === 'draft' && r.machine_sn ? { ...r, syncStatus: 'synced' } : r));
      setStatusMsg({ type: 'success', text: `同步成功！已上传 ${draftRows.length} 条数据。` });
      setRemoteAssets(prev => [...committedRows, ...prev]);

    } catch (e) {
      setStatusMsg({ type: 'error', text: '同步失败，请检查网络连接。' });
    } finally {
      setIsSyncing(false);
    }
  };

  const handleExcelImport = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (files && files[0]) {
      const file = files[0];
      
      // Limit to 1MB
      if (file.size > 1024 * 1024) {
        setStatusMsg({ type: 'error', text: "文件大小不能超过 1MB" });
        e.target.value = '';
        return;
      }

      const reader = new FileReader();
      reader.onload = async (evt) => {
        try {
          const XLSX = await import('xlsx');
          const wb = XLSX.read(evt.target?.result, { type: 'array' });
          const data = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]]);
          
          if (!data || data.length === 0) {
             throw new Error("无数据");
          }

          const mappedRows: GridRow[] = data.map((d: any, idx: number) => ({
             _id: `imp_${idx}_${Date.now()}`,
             contract_no: d['合同号'] || '',
             invoice_date: d['发货日期'] || '',
             model: d['型号'] || '',
             machine_sn: d['SN'] || '', 
             mb_model: d['主板型号'] || '',
             mb_sn: d['SN_1'] || '', 
             cpu_model: d['CPU型号'] || '',
             cpu_sn: d['CPU序列号'] || '',
             cpu_sn_2: d['CPU序列号_1'] || '',
             psu_info: d['电源品牌、型号'] || '',
             psu_cage_sn: d['SN_2'] || '', 
             psu_module_1_sn: d['模块1'] || '',
             psu_module_2_sn: d['模块2'] || '',
             hdd_info: d['硬盘'] || '',
             hdd_sn: d['SN_3'] || '',
             mem_info: d['内存品牌、主频'] || '',
             mem_sns: ``, // Simplified
             pcie_sn: d['PCIE'] || '',
             syncStatus: 'draft' as const // Import as draft
          }));
          
          setRows(prev => [...prev.filter(r => r.machine_sn), ...mappedRows]);
          setActiveTab('scan');
          setStatusMsg({ type: 'success', text: `已导入 ${mappedRows.length} 条数据 (草稿)` });
        } catch (err: any) { 
           console.error(err);
           setStatusMsg({ type: 'error', text: `导入出错: ${err.message}` });
        }
      };
      reader.onerror = () => {
         setStatusMsg({ type: 'error', text: "文件读取失败" });
      };
      reader.readAsArrayBuffer(file);
      e.target.value = '';
    }
  };

  // Counters
  const pendingCount = rows.filter(r => r.syncStatus === 'draft' && r.machine_sn).length;
  const syncedCount = rows.filter(r => r.syncStatus === 'synced').length;

  return (
    <div className="space-y-6">
      {scanDialog && <div className="fixed inset-0 z-[80] grid place-items-center bg-slate-950/45 p-4" role="dialog" aria-modal="true" aria-label="扫码录入"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-700">SCAN STEP</p><h2 className="mt-1 text-xl font-bold text-slate-900">扫描：{runtimeFields.find(field => field.key === scanDialog.field)?.label || scanDialog.field}</h2><p className="mt-1 text-sm text-slate-500">该流程被模板标记为需要扫码，扫码完成后将自动保存并记录操作员工号。</p></div><button type="button" onClick={() => setScanDialog(null)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100" aria-label="关闭"><X size={18} /></button></div><input autoFocus value={scanDialog.value} onChange={event => setScanDialog(previous => previous ? { ...previous, value: event.target.value } : previous)} onKeyDown={event => { if (event.key === 'Enter') { event.preventDefault(); void confirmScanDialog(); } }} placeholder="请扫描或输入 SN" className="mt-5 w-full rounded-xl border-2 border-cyan-200 px-4 py-3 font-mono text-lg outline-none focus:border-cyan-600 focus:ring-4 focus:ring-cyan-100" /><div className="mt-5 flex justify-end gap-3"><button type="button" onClick={() => setScanDialog(null)} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-600">取消</button><button type="button" onClick={() => void confirmScanDialog()} className="rounded-lg bg-cyan-700 px-5 py-2 text-sm font-semibold text-white hover:bg-cyan-800">确认并保存</button></div></div></div>}
      {/* Hidden Label Template */}
      <div 
         className="printable-content fixed top-0 left-0 -z-50 opacity-0" 
         style={{ width: '100mm', height: '60mm', overflow: 'hidden', fontFamily: 'Arial, sans-serif' }}
      >
        {labelToPrint && (
           <div className="w-full h-full p-2 border-2 border-black flex flex-col justify-between box-border bg-white text-black">
              <div className="flex justify-between items-start">
                 <div>
                    <h1 className="text-xl font-bold tracking-tighter">SERVER TAG</h1>
                    <p className="text-xs font-bold mt-1">SN: <span className="text-lg font-mono">{labelToPrint.machine_sn}</span></p>
                    <p className="text-xs mt-1">Model: {labelToPrint.model}</p>
                 </div>
                 <div className="w-20 h-20 bg-white">
                    {/* Use a public QR code API for the label */}
                    <img 
                       src={`https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=${labelToPrint.machine_sn}`} 
                       alt="QR" 
                       className="w-full h-full object-contain" 
                    />
                 </div>
              </div>
              
              <div className="grid grid-cols-2 gap-1 text-[10px] leading-tight mt-2 border-t border-black pt-1">
                 <div>
                    <span className="font-bold">CPU:</span> {labelToPrint.cpu_model || 'N/A'}
                 </div>
                 <div>
                    <span className="font-bold">MEM:</span> {labelToPrint.mem_info ? 'Included' : '-'}
                 </div>
                 <div>
                    <span className="font-bold">HDD:</span> {labelToPrint.hdd_info ? 'Included' : '-'}
                 </div>
                 <div>
                    <span className="font-bold">Date:</span> {new Date().toLocaleDateString()}
                 </div>
              </div>

              <div className="text-[9px] text-center mt-auto font-bold uppercase tracking-widest">
                 TIGERWAY INNOVATION
              </div>
           </div>
        )}
      </div>

      {/* Header */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 flex items-center">
             <ScanLine className="mr-2 text-blue-600" /> 生产录入系统
          </h1>
          <div className="flex items-center text-xs text-gray-500 mt-1 space-x-3">
             <span className="flex items-center">
               <Database className="w-3 h-3 mr-1" /> 本地缓存 (Atomic Save): 
               <span className="ml-1 font-mono text-gray-700">{lastSavedTime || 'Pending...'}</span>
             </span>
             <span className="flex items-center">
               {isOnline ? <Wifi className="w-3 h-3 mr-1 text-green-500"/> : <WifiOff className="w-3 h-3 mr-1 text-red-500"/>}
               {isOnline ? '网络在线' : '离线模式 (Offline)'}
             </span>
          </div>
        </div>
        
        <div className="flex space-x-3 items-center">
           <button
             type="button"
             onClick={() => { setShowBatchSettings(previous => !previous); setMachineSearch(''); }}
             disabled={!selectedTemplate || !rows.length}
             className={`flex items-center gap-1 rounded border px-3 py-2 text-sm font-semibold transition-colors ${showBatchSettings ? 'border-cyan-600 bg-cyan-600 text-white' : 'border-cyan-300 bg-cyan-50 text-cyan-800 hover:bg-cyan-100'} disabled:cursor-not-allowed disabled:opacity-40`}
             title="查看并编辑当前批次全部明细"
           >
             <Database size={16} />{showBatchSettings ? '关闭设置' : '设置'}
           </button>
           <button 
             onClick={() => setSoundEnabled(!soundEnabled)}
             className={`p-2 rounded border transition-colors ${soundEnabled ? 'bg-blue-50 text-blue-600 border-blue-200' : 'bg-gray-100 text-gray-400 border-gray-200'}`}
             title={soundEnabled ? "提示音: 开" : "提示音: 关"}
           >
             {soundEnabled ? <Volume2 size={20}/> : <VolumeX size={20}/>}
           </button>
           <div className="flex rounded-md shadow-sm">
             <span className="inline-flex items-center px-3 rounded-l-md border border-r-0 border-gray-300 bg-gray-50 text-gray-500 text-sm">
               批次号
             </span>
             <input 
                type="text" 
                value={batchName}
                onChange={(e) => setBatchName(e.target.value)}
                className="flex-1 min-w-0 block w-48 px-3 py-2 rounded-none rounded-r-md border border-gray-300 sm:text-sm focus:ring-blue-500 focus:border-blue-500"
             />
           </div>
        </div>
      </div>

      {statusMsg && (
        <div className={`border px-4 py-3 rounded flex justify-between items-center animate-in slide-in-from-top-2 ${
           statusMsg.type === 'error' ? 'bg-red-50 border-red-200 text-red-800' :
           statusMsg.type === 'success' ? 'bg-green-50 border-green-200 text-green-800' :
           'bg-blue-50 border-blue-200 text-blue-800'
        }`}>
          <div className="flex items-center">
             {statusMsg.type === 'error' && <AlertCircle className="w-4 h-4 mr-2"/>}
             {statusMsg.type === 'success' && <Check className="w-4 h-4 mr-2"/>}
             <span>{statusMsg.text}</span>
          </div>
          <button onClick={() => setStatusMsg(null)} className="opacity-50 hover:opacity-100"><X className="w-4 h-4"/></button>
        </div>
      )}

      {columnDialog && (
        <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/45 p-4" role="dialog" aria-modal="true" aria-labelledby="add-column-title">
          <div className="w-full max-w-md rounded-2xl border border-cyan-200 bg-white p-6 shadow-2xl">
            <div className="flex items-start justify-between gap-4">
              <div>
                <h2 id="add-column-title" className="text-lg font-bold text-slate-900">批量添加扫码列</h2>
                <p className="mt-1 text-xs text-slate-500">在当前列右侧连续添加相同名称的列，SN 列会自动带操作员列。</p>
              </div>
              <button type="button" onClick={() => setColumnDialog(null)} className="rounded-lg p-1 text-slate-400 hover:bg-slate-100 hover:text-slate-700" aria-label="关闭"><X size={18} /></button>
            </div>
            <label className="mt-5 block text-sm font-semibold text-slate-700">列名称</label>
            <input autoFocus value={columnDialog.label} onChange={event => setColumnDialog(previous => previous ? { ...previous, label: event.target.value } : previous)} placeholder="例如：内存 SN、网卡型号" className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm outline-none focus:border-cyan-500 focus:ring-2 focus:ring-cyan-100" />
            <label className="mt-4 block text-sm font-semibold text-slate-700">添加数量</label>
            <input type="number" min={1} max={50} step={1} value={columnDialog.count} onChange={event => setColumnDialog(previous => previous ? { ...previous, count: event.target.value } : previous)} className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm outline-none focus:border-cyan-500 focus:ring-2 focus:ring-cyan-100" />
            <p className="mt-2 text-xs text-slate-500">支持 1–50 列，新增列会立即同步到服务器。</p>
            <div className="mt-6 flex justify-end gap-3">
              <button type="button" onClick={() => setColumnDialog(null)} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-50">取消</button>
              <button type="button" onClick={confirmRuntimeColumns} className="rounded-lg bg-cyan-700 px-4 py-2 text-sm font-semibold text-white hover:bg-cyan-800">确认添加</button>
            </div>
          </div>
        </div>
      )}

      <div className={`bg-white rounded-lg shadow border transition-all duration-200 overflow-hidden ${lastScanStatus === 'error' ? 'ring-4 ring-red-300' : lastScanStatus === 'success' ? 'ring-4 ring-green-300' : 'border-gray-200'}`}>
         {/* Tabs */}
         <div className="flex border-b border-gray-200">
           <button onClick={() => setActiveTab('scan')} className={`flex-1 py-4 px-6 text-center font-medium text-sm ${activeTab === 'scan' ? 'text-blue-600 border-b-2 border-blue-600 bg-blue-50' : 'text-gray-500 hover:text-gray-700'}`}>扫码/网格录入</button>
           <button onClick={() => setActiveTab('import')} className={`flex-1 py-4 px-6 text-center font-medium text-sm ${activeTab === 'import' ? 'text-blue-600 border-b-2 border-blue-600 bg-blue-50' : 'text-gray-500 hover:text-gray-700'}`}>Excel 批量导入</button>
         </div>

         <div className="p-0">
           {activeTab === 'import' && (
             <div className="p-10 text-center">
                <div className="border-2 border-dashed border-gray-300 rounded-lg p-12 hover:bg-gray-50 transition-colors inline-block w-full max-w-2xl">
                  <FileSpreadsheet className="mx-auto h-12 w-12 text-gray-400" />
                  <label className="mt-4 block cursor-pointer">
                    <span className="bg-blue-600 text-white px-4 py-2 rounded shadow hover:bg-blue-700 transition">选择 Excel 文件</span>
                    <input type="file" className="hidden" accept=".xlsx,.xls" onChange={handleExcelImport} />
                  </label>
                </div>
             </div>
           )}

           {activeTab === 'scan' && (
             <div className="relative overflow-visible">
               <div className="flex flex-wrap items-center justify-between gap-3 border-b border-blue-100 bg-blue-50/50 p-4">
                  <div className="text-sm text-blue-800 flex items-center">
                     <span className="font-bold mr-2">操作指引:</span> 
                     <span className="bg-white border border-blue-200 px-2 py-0.5 rounded text-xs font-mono mr-1">Enter</span> 跳格 
                  </div>
                  <div className="flex items-center gap-3 rounded-lg border border-blue-200 bg-white px-3 py-1.5 text-xs font-semibold text-slate-700">
                    <span className="text-blue-800">扫码后跳转：</span>
                    <label className="flex cursor-pointer items-center gap-1.5">
                      <input type="radio" name="scan-jump-mode" checked={scanJumpMode === 'horizontal'} onChange={() => { setScanJumpMode('horizontal'); localStorage.setItem('slss_scan_jump_mode', 'horizontal'); }} className="text-blue-600 focus:ring-blue-500" />
                      下一列 SN
                    </label>
                    <label className="flex cursor-pointer items-center gap-1.5">
                      <input type="radio" name="scan-jump-mode" checked={scanJumpMode === 'vertical'} onChange={() => { setScanJumpMode('vertical'); localStorage.setItem('slss_scan_jump_mode', 'vertical'); }} className="text-blue-600 focus:ring-blue-500" />
                      下一行同配件 SN
                    </label>
                  </div>
                  <div className="order-last ml-auto flex items-center gap-2 rounded-xl border-2 border-cyan-500 bg-cyan-50 px-3 py-2 shadow-sm">
                    <label htmlFor="machine-sn-search" className="whitespace-nowrap text-sm font-bold text-cyan-900">整机 SN</label>
                    <input id="machine-sn-search" value={machineSearch} onChange={e => handleMachineSearchChange(e.target.value)} onBlur={commitMachineSearch} onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); void commitMachineSearch(); } }} placeholder="输入或扫描整机 SN" className="w-64 rounded-lg border border-cyan-300 bg-white px-3 py-2 text-base font-semibold outline-none ring-cyan-500 placeholder:font-normal placeholder:text-slate-400 focus:ring-2" />
                    {machineSearch && <button onClick={() => setMachineSearch('')} className="whitespace-nowrap text-xs font-semibold text-cyan-700 hover:underline">清除</button>}
                  </div>
               </div>
               
               {selectedTemplate && !machineSearch.trim() && !showBatchSettings && <div className="rounded-xl border border-dashed border-cyan-300 bg-cyan-50 px-6 py-12 text-center text-sm text-cyan-800">请先输入或扫描整机 SN，系统将仅显示该设备尚未完工的组装、高温间测试和包装流程；点击“设置”可查看并编辑当前批次全部明细。</div>}
               {selectedTemplate && machineSearch.trim() && !showBatchSettings && !visibleRows.length && <div className="rounded-xl border border-dashed border-amber-300 bg-amber-50 px-6 py-12 text-center text-sm text-amber-800">未找到已保存的整机 SN“{machineSearch}”，请确认流程单仍有空白设备行，或清除后重新输入。</div>}
               {selectedTemplate && (machineSearch.trim() || showBatchSettings) && visibleRows.length > 0 && (
                 <>
                     {showBatchSettings && <div className="border-b border-cyan-100 bg-cyan-50 px-4 py-3 text-sm text-cyan-900"><b>批次设置</b>：当前显示该批次全部设备明细，可直接编辑并自动保存；已完工行仍受完工修改权限控制。</div>}
                     <TemplateGrid
                     rows={visibleRows}
                     template={{ ...selectedTemplate, fields: runtimeFields }}
                     onChange={handleTemplateCellChange}
                     onKeyDown={handleKeyDown}
                     onDelete={deleteRow}
                     onAddColumn={insertRuntimeColumn}
                     onDeleteColumn={deleteRuntimeColumn}
                     onComplete={completeRow}
                     onCompleteSection={completeSection}
                     canAddColumn={canAddColumn}
                     canDeleteColumn={canDeleteColumn}
                     canForceComplete={canForceComplete}
                     onBlur={handleTemplateBlur}
                     onScanRequired={openScanDialog}
                     onStepToggle={toggleStep}
                     dispatchOrderNo={dispatchOrderNo}
                   />
                 </>
               )}
               <div className={`${selectedTemplate ? 'hidden' : ''} w-full overflow-x-scroll pb-4`}>
                 <table className="w-full divide-y divide-gray-200" style={{ minWidth: '2200px' }}>
                  <thead className="bg-gray-50">
                    <tr>
                      <th className="bg-gray-50 z-10 px-3 py-3 text-center text-xs font-medium text-gray-500 uppercase w-10 border-r">No.</th>
                      <th className="bg-gray-50 z-10 px-3 py-3 text-center text-xs font-bold text-gray-700 uppercase w-16 border-r shadow-sm">状态</th>
                      <th className="sticky left-0 bg-yellow-50 z-20 px-3 py-3 text-left text-xs font-bold text-gray-700 uppercase w-40 border-r shadow-[2px_0_4px_rgba(15,23,42,.12)]">整机 SN</th>
                      <th className="px-3 py-3 text-left text-xs font-medium text-gray-500 uppercase w-32">合同号</th>
                      <th className="px-3 py-3 text-left text-xs font-medium text-gray-500 uppercase w-32">型号</th>
                      <th className="px-3 py-3 text-left text-xs font-medium text-gray-500 uppercase w-32 bg-gray-50/50">主板型号</th>
                      <th className="px-3 py-3 text-left text-xs font-medium text-gray-500 uppercase w-32 bg-gray-50/50">主板 SN</th>
                      <th className="px-3 py-3 text-left text-xs font-medium text-cyan-700 uppercase w-28">主板操作员</th>
                      <th className="px-3 py-3 text-left text-xs font-medium text-gray-500 uppercase w-24">CPU型号</th>
                      <th className="px-3 py-3 text-left text-xs font-medium text-gray-500 uppercase w-32">CPU1 SN</th>
                      <th className="px-3 py-3 text-left text-xs font-medium text-cyan-700 uppercase w-28">CPU操作员</th>
                      <th className="px-3 py-3 text-left text-xs font-medium text-gray-500 uppercase w-32">CPU2 SN</th>
                      <th className="px-3 py-3 text-left text-xs font-medium text-cyan-700 uppercase w-28">CPU2操作员</th>
                      <th className="px-3 py-3 text-left text-xs font-medium text-gray-500 uppercase w-32 bg-gray-50/50">电源信息</th>
                      <th className="px-3 py-3 text-left text-xs font-medium text-gray-500 uppercase w-32 bg-gray-50/50">电源笼 SN</th>
                      <th className="px-3 py-3 text-left text-xs font-medium text-cyan-700 uppercase w-28">电源操作员</th>
                      <th className="px-3 py-3 text-left text-xs font-medium text-gray-500 uppercase w-32 bg-gray-50/50">模块1 SN</th>
                      <th className="px-3 py-3 text-left text-xs font-medium text-cyan-700 uppercase w-28">模块1操作员</th>
                      <th className="px-3 py-3 text-left text-xs font-medium text-gray-500 uppercase w-32 bg-gray-50/50">模块2 SN</th>
                      <th className="px-3 py-3 text-left text-xs font-medium text-cyan-700 uppercase w-28">模块2操作员</th>
                      <th className="px-3 py-3 text-left text-xs font-medium text-gray-500 uppercase w-32">硬盘 SN</th>
                      <th className="px-3 py-3 text-left text-xs font-medium text-cyan-700 uppercase w-28">硬盘操作员</th>
                      <th className="px-3 py-3 text-left text-xs font-medium text-gray-500 uppercase w-32">内存信息</th>
                      <th className="px-3 py-3 text-left text-xs font-medium text-gray-500 uppercase w-48">内存 SN(s)</th>
                      <th className="px-3 py-3 text-left text-xs font-medium text-cyan-700 uppercase w-28">内存操作员</th>
                      <th className="px-3 py-3 text-left text-xs font-medium text-gray-500 uppercase w-32 bg-purple-50">PCIE SN</th>
                      <th className="px-3 py-3 text-left text-xs font-medium text-cyan-700 uppercase w-28">PCIE操作员</th>
                      <th className="px-3 py-3 text-center text-xs font-medium text-gray-500 uppercase w-20 sticky right-0 bg-gray-50">操作</th>
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-gray-200">
                    {rows.map((row, idx) => (
                      <tr key={row._id} className="hover:bg-gray-50 group">
                        <td className="bg-white px-3 py-2 text-xs text-gray-400 text-center border-r">{idx + 1}</td>
                        
                        {/* Status Column */}
                        <td className="bg-white p-1 text-center border-r shadow-sm">
                           {row.syncStatus === 'synced' ? (
                              <div className="flex justify-center text-green-500" title="已同步 (Cloud)"><Cloud className="w-5 h-5 fill-current" /></div>
                           ) : (
                              row.machine_sn ? <div className="flex justify-center text-gray-400" title="本地草稿 (Draft)"><Check className="w-5 h-5" /></div> : <div className="w-5 h-5 rounded-full border border-gray-200 mx-auto"></div>
                           )}
                        </td>

                        <td className="sticky left-0 bg-yellow-50 z-20 p-1 border-r shadow-[2px_0_4px_rgba(15,23,42,.12)]">
                           <input 
                            className={`scanner-input w-full border-0 border-b-2 border-transparent focus:border-blue-500 focus:ring-0 bg-transparent text-sm font-bold p-1 transition-colors focus:bg-white ${row.syncStatus === 'synced' ? 'text-green-700' : 'text-gray-900'}`}
                            value={row.machine_sn}
                            placeholder="SN..."
                            onKeyDown={(e) => handleKeyDown(e, row._id)}
                            onChange={e => handleCellChange(row._id, 'machine_sn', e.target.value)}
                          />
                        </td>
                        
                        {/* Fields */}
                        <td className="p-1"><input className="scanner-input w-full bg-transparent text-xs p-1 focus:bg-white" value={row.contract_no} onKeyDown={(e) => handleKeyDown(e, row._id)} onChange={e => handleCellChange(row._id, 'contract_no', e.target.value)} /></td>
                        <td className="p-1"><input className="scanner-input w-full bg-transparent text-xs p-1 focus:bg-white" value={row.model} onKeyDown={(e) => handleKeyDown(e, row._id)} onChange={e => handleCellChange(row._id, 'model', e.target.value)} /></td>
                        <td className="p-1 bg-gray-50/30"><input className="scanner-input w-full bg-transparent text-xs p-1 focus:bg-white" value={row.mb_model || ''} onKeyDown={(e) => handleKeyDown(e, row._id)} onChange={e => handleCellChange(row._id, 'mb_model', e.target.value)} /></td>
                        <td className="p-1 bg-gray-50/30"><input className="scanner-input w-full bg-transparent text-xs p-1 focus:bg-white" value={row.mb_sn || ''} onKeyDown={(e) => handleKeyDown(e, row._id)} onChange={e => handleCellChange(row._id, 'mb_sn', e.target.value)} /></td>
                        <td className="p-1 bg-cyan-50/40 text-xs text-cyan-800">{row.mb_sn_operator || '—'}</td>
                        <td className="p-1"><input className="scanner-input w-full bg-transparent text-xs p-1 focus:bg-white" value={row.cpu_model || ''} onKeyDown={(e) => handleKeyDown(e, row._id)} onChange={e => handleCellChange(row._id, 'cpu_model', e.target.value)} /></td>
                        <td className="p-1"><input className="scanner-input w-full bg-transparent text-xs p-1 focus:bg-white" value={row.cpu_sn || ''} onKeyDown={(e) => handleKeyDown(e, row._id)} onChange={e => handleCellChange(row._id, 'cpu_sn', e.target.value)} /></td>
                        <td className="p-1 bg-cyan-50/40 text-xs text-cyan-800">{row.cpu_sn_operator || '—'}</td>
                        <td className="p-1"><input className="scanner-input w-full bg-transparent text-xs p-1 focus:bg-white" value={row.cpu_sn_2 || ''} onKeyDown={(e) => handleKeyDown(e, row._id)} onChange={e => handleCellChange(row._id, 'cpu_sn_2', e.target.value)} /></td>
                        <td className="p-1 bg-cyan-50/40 text-xs text-cyan-800">{row.cpu_sn_2_operator || '—'}</td>
                        <td className="p-1 bg-gray-50/30"><input className="scanner-input w-full bg-transparent text-xs p-1 focus:bg-white" value={row.psu_info || ''} onKeyDown={(e) => handleKeyDown(e, row._id)} onChange={e => handleCellChange(row._id, 'psu_info', e.target.value)} /></td>
                        <td className="p-1 bg-gray-50/30"><input className="scanner-input w-full bg-transparent text-xs p-1 focus:bg-white" value={row.psu_cage_sn || ''} onKeyDown={(e) => handleKeyDown(e, row._id)} onChange={e => handleCellChange(row._id, 'psu_cage_sn', e.target.value)} /></td>
                        <td className="p-1 bg-cyan-50/40 text-xs text-cyan-800">{row.psu_cage_sn_operator || '—'}</td>
                        <td className="p-1 bg-gray-50/30"><input className="scanner-input w-full bg-transparent text-xs p-1 focus:bg-white" value={row.psu_module_1_sn || ''} onKeyDown={(e) => handleKeyDown(e, row._id)} onChange={e => handleCellChange(row._id, 'psu_module_1_sn', e.target.value)} /></td>
                        <td className="p-1 bg-cyan-50/40 text-xs text-cyan-800">{row.psu_module_1_sn_operator || '—'}</td>
                        <td className="p-1 bg-gray-50/30"><input className="scanner-input w-full bg-transparent text-xs p-1 focus:bg-white" value={row.psu_module_2_sn || ''} onKeyDown={(e) => handleKeyDown(e, row._id)} onChange={e => handleCellChange(row._id, 'psu_module_2_sn', e.target.value)} /></td>
                        <td className="p-1 bg-cyan-50/40 text-xs text-cyan-800">{row.psu_module_2_sn_operator || '—'}</td>
                        <td className="p-1"><input className="scanner-input w-full bg-transparent text-xs p-1 focus:bg-white" value={row.hdd_sn || ''} onKeyDown={(e) => handleKeyDown(e, row._id)} onChange={e => handleCellChange(row._id, 'hdd_sn', e.target.value)} /></td>
                        <td className="p-1 bg-cyan-50/40 text-xs text-cyan-800">{row.hdd_sn_operator || '—'}</td>
                        <td className="p-1"><input className="scanner-input w-full bg-transparent text-xs p-1 focus:bg-white" value={row.mem_info || ''} onKeyDown={(e) => handleKeyDown(e, row._id)} onChange={e => handleCellChange(row._id, 'mem_info', e.target.value)} /></td>
                        <td className="p-1"><input className="scanner-input w-full bg-transparent text-xs p-1 focus:bg-white" value={row.mem_sns || ''} onKeyDown={(e) => handleKeyDown(e, row._id)} onChange={e => handleCellChange(row._id, 'mem_sns', e.target.value)} /></td>
                        <td className="p-1 bg-cyan-50/40 text-xs text-cyan-800">{row.mem_sns_operator || '—'}</td>
                        <td className="p-1 bg-purple-50/30"><input className="scanner-input w-full bg-transparent text-xs p-1 font-medium text-purple-700 focus:bg-white" value={row.pcie_sn || ''} onKeyDown={(e) => handleKeyDown(e, row._id)} onChange={e => handleCellChange(row._id, 'pcie_sn', e.target.value)} /></td>
                        <td className="p-1 bg-cyan-50/40 text-xs text-cyan-800">{row.pcie_sn_operator || '—'}</td>

                        <td className="sticky right-0 bg-white z-10 px-3 py-2 text-center border-l flex space-x-1 justify-center">
                          {row.syncStatus === 'synced' && (
                             <button onClick={() => handlePrintLabel(row)} className="text-gray-300 hover:text-blue-600 p-1" title="打印标签">
                                <Printer className="w-4 h-4" />
                             </button>
                          )}
                          <button onClick={() => deleteRow(row._id)} className="text-gray-300 hover:text-red-500 p-1" title="删除行">
                             <Trash2 className="w-4 h-4" />
                          </button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
               </div>
             </div>
           )}
         </div>

         <div className="bg-gray-50 p-4 border-t border-gray-200 flex justify-between items-center">
            <div className="text-xs text-gray-500 flex items-center space-x-4">
              <span className="flex items-center"><Check className="w-3 h-3 mr-1"/> 待同步: {pendingCount}</span>
              <span className="flex items-center text-green-600"><Cloud className="w-3 h-3 mr-1"/> 已同步: {syncedCount}</span>
            </div>
            <div className="flex space-x-3">
               <button onClick={() => addNewRow(true)} className="bg-white border border-gray-300 text-gray-700 px-4 py-2 rounded shadow-sm hover:bg-gray-50 flex items-center text-sm font-medium">
                 <Plus className="w-4 h-4 mr-2" /> 新增一行
               </button>
               <div className={`flex items-center rounded px-4 py-2 text-sm font-semibold ${isOnline ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>
                 <Cloud className="mr-2 h-4 w-4" />{isOnline ? '自动保存与自动同步已启用' : '网络离线，本地自动保存中'}
               </div>
            </div>
         </div>
      </div>
    </div>
  );
};

export default ProductionEntry;
