import React,{useEffect,useState} from 'react';
import {api} from '../services/apiClient';
import {Briefcase,Plus,RefreshCw,ArrowRight,PackageSearch,Server,Boxes,Trash2,CheckCircle2,X} from 'lucide-react';
import {useAuth} from '../components/AuthContext';

const labels:Record<string,string>={DRAFT:'草稿',SUBMITTED:'已提交',SALES_REVIEW:'销售复核',PROCUREMENT_PENDING:'待采购',QUOTING:'询价中',QUOTED:'已报价',APPROVED:'已批准',REJECTED:'已驳回',CANCELLED:'已取消'};
const inputClass='mt-1.5 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-cyan-600 focus:ring-2 focus:ring-cyan-100';

const SalesProcurement:React.FC=()=>{
 const {user}=useAuth(); const canProcure=!!user?.permissions.includes('MANAGE_PROCUREMENT'); const canSell=!!user?.permissions.includes('MANAGE_SALES');
 const [rows,setRows]=useState<any[]>([]),[projects,setProjects]=useState<any[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[show,setShow]=useState(false);
 const [selected,setSelected]=useState<any|null>(null),[selectedProject,setSelectedProject]=useState<any|null>(null);
 const [servers,setServers]=useState<any[]>([]),[software,setSoftware]=useState<any[]>([]),[quotes,setQuotes]=useState<any[]>([]);
 const [form,setForm]=useState({customerName:'',projectName:'',quantity:1,requestedDeliveryDate:'',deliveryLocation:'',technicalSummary:'',softwareSummary:'',priority:'NORMAL'});
 const [serverForm,setServerForm]=useState({serverModel:'',quantity:1,cpuRequirement:'',memoryRequirement:'',storageRequirement:'',networkRequirement:'',customDescription:''});
 const [softwareForm,setSoftwareForm]=useState({osName:'',osVersion:'',middleware:'',databaseRequirement:'',licenseRequirement:'',securityRequirement:''});
 const [quoteForm,setQuoteForm]=useState({supplierName:'',amount:'',currency:'CNY',deliveryDate:'',validityDate:'',notes:''});
 const load=()=>{setLoading(true);setError('');Promise.all([api.salesInitiations(),canProcure?api.procurementProjects():Promise.resolve([])]).then(([a,b])=>{setRows(a as any[]);setProjects(b);}).catch(e=>setError(e.message||'工作流数据加载失败')).finally(()=>setLoading(false));};
 useEffect(load,[]);
 const openRequirements=async(x:any)=>{setSelected(x);setSelectedProject(null);setError('');try{const [a,b]=await Promise.all([api.serverRequirements(x.id),api.softwareRequirements(x.id)]);setServers(a);setSoftware(b);}catch(e:any){setError(e.message);}};
 const openProject=async(p:any)=>{setSelectedProject(p);setSelected(null);setError('');try{setQuotes(await api.procurementQuotations(p.id));}catch(e:any){setError(e.message);}};
 const create=async()=>{if(!form.customerName.trim()||!form.projectName.trim()||form.quantity<1){setError('客户、项目名称和数量为必填项');return;}try{await api.createSalesInitiation({...form,requestedDeliveryDate:form.requestedDeliveryDate||null});setShow(false);load();}catch(e:any){setError(e.message);}};
 const submit=async(id:number)=>{try{await api.transitionSalesInitiation(id,'SUBMITTED','提交销售立项');setSelected(null);load();}catch(e:any){setError(e.message);}};
 const addServer=async()=>{if(!selected||!serverForm.serverModel||serverForm.quantity<1)return setError('服务器型号和数量为必填项');try{await api.addServerRequirement(selected.id,serverForm);setServers(await api.serverRequirements(selected.id));setServerForm({...serverForm,serverModel:'',quantity:1});}catch(e:any){setError(e.message);}};
 const addSoftware=async()=>{if(!selected||!softwareForm.osName)return setError('操作系统名称不能为空');try{await api.addSoftwareRequirement(selected.id,softwareForm);setSoftware(await api.softwareRequirements(selected.id));setSoftwareForm({osName:'',osVersion:'',middleware:'',databaseRequirement:'',licenseRequirement:'',securityRequirement:''});}catch(e:any){setError(e.message);}};
 const removeServer=async(id:number)=>{if(!selected)return;try{await api.deleteServerRequirement(selected.id,id);setServers(servers.filter(x=>x.id!==id));}catch(e:any){setError(e.message);}};
 const removeSoftware=async(id:number)=>{if(!selected)return;try{await api.deleteSoftwareRequirement(selected.id,id);setSoftware(software.filter(x=>x.id!==id));}catch(e:any){setError(e.message);}};
 const addQuote=async()=>{if(!selectedProject||!quoteForm.supplierName||Number(quoteForm.amount)<=0)return setError('供应商和有效报价金额为必填项');try{await api.createQuotation(selectedProject.id,{...quoteForm,amount:Number(quoteForm.amount),deliveryDate:quoteForm.deliveryDate||null,validityDate:quoteForm.validityDate||null});setQuotes(await api.procurementQuotations(selectedProject.id));setQuoteForm({...quoteForm,supplierName:'',amount:'',notes:''});load();}catch(e:any){setError(e.message);}};
 const selectQuote=async(id:number)=>{if(!selectedProject)return;try{const p=await api.selectQuotation(selectedProject.id,id);setSelectedProject(p);setQuotes(await api.procurementQuotations(selectedProject.id));load();}catch(e:any){setError(e.message);}};

 return <div className="min-h-full bg-[#eef2f3] p-4 md:p-7">
  <header className="relative overflow-hidden rounded-2xl bg-[#0c1824] px-6 py-7 text-white shadow-xl"><div className="absolute right-0 top-0 h-full w-1/3 bg-[linear-gradient(135deg,transparent_35%,rgba(34,211,238,.12)_35%,rgba(34,211,238,.12)_38%,transparent_38%)]"/><p className="text-xs font-bold uppercase tracking-[.28em] text-cyan-300">Commercial Control Plane</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold tracking-tight">销售立项与采购协同</h1><p className="mt-2 max-w-2xl text-sm text-slate-300">需求配置、交付约束、询价比选，全流程由事务状态机驱动。</p></div>{canSell&&<button onClick={()=>setShow(true)} className="flex items-center gap-2 rounded-lg bg-cyan-400 px-4 py-2.5 text-sm font-bold text-slate-950 hover:bg-cyan-300"><Plus size={17}/>新建立项</button>}</div></header>
  {error&&<div role="alert" className="mt-4 flex justify-between rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><span>{error}</span><button onClick={()=>setError('')}><X size={16}/></button></div>}
  <div className="mt-6 grid gap-6 xl:grid-cols-[1.45fr_.85fr]">
   <section className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b px-5 py-4"><h2 className="flex items-center gap-2 font-semibold text-slate-800"><Briefcase size={18} className="text-cyan-700"/>立项队列</h2><button onClick={load}><RefreshCw size={16} className={loading?'animate-spin':''}/></button></div>{loading?<div className="p-10 text-center text-sm text-slate-500">正在同步业务状态…</div>:rows.length===0?<div className="p-10 text-center text-sm text-slate-500">暂无销售立项</div>:<div className="divide-y">{rows.map(x=><article key={x.id} onClick={()=>canSell&&openRequirements(x)} className={`grid gap-3 px-5 py-4 md:grid-cols-[1fr_auto] ${canSell?'cursor-pointer ':''}${selected?.id===x.id?'bg-cyan-50':'hover:bg-slate-50'}`}><div><div className="flex items-center gap-3"><span className="font-mono text-xs text-cyan-700">{x.initiationNo}</span><span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs">{labels[x.status]||x.status}</span></div><h3 className="mt-1 font-semibold">{x.projectName}</h3><p className="mt-1 text-sm text-slate-500">{x.customerName} · {x.quantity} 台 · 交付 {x.requestedDeliveryDate||'待确认'}</p></div>{canSell&&x.status==='DRAFT'&&<button onClick={e=>{e.stopPropagation();submit(x.id)}} className="self-center rounded-md border border-cyan-700 px-3 py-2 text-xs font-semibold text-cyan-800">提交审核 <ArrowRight className="ml-1 inline" size={14}/></button>}</article>)}</div>}</section>
   <section className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b px-5 py-4"><h2 className="flex items-center gap-2 font-semibold"><PackageSearch size={18} className="text-amber-600"/>采购项目</h2></div>{!canProcure?<p className="p-8 text-center text-sm text-slate-500">采购项目由采购角色处理</p>:projects.length===0?<p className="p-8 text-center text-sm text-slate-500">立项进入待采购后自动生成</p>:<div className="divide-y">{projects.map(p=><button key={p.id} onClick={()=>openProject(p)} className={`block w-full p-5 text-left ${selectedProject?.id===p.id?'bg-amber-50':'hover:bg-slate-50'}`}><div className="flex justify-between"><span className="font-mono text-sm font-semibold">{p.projectNo}</span><span className="text-xs text-amber-700">{p.status}</span></div><p className="mt-2 text-xs text-slate-500">报价截止：{p.quotationDeadline||'待设置'}</p><p className="mt-1 text-sm">中选：{p.selectedSupplier||'尚未中选'}</p></button>)}</div>}</section>
  </div>

  {selected&&<section className="mt-6 rounded-2xl border border-cyan-900/10 bg-[#101d29] p-5 text-white shadow-xl"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.22em] text-cyan-300">Requirement Workshop</p><h2 className="mt-1 text-xl font-semibold">{selected.projectName} · 配置明细</h2></div><span className="rounded-full bg-white/10 px-3 py-1 text-xs">{labels[selected.status]}</span></div><div className="mt-5 grid gap-5 xl:grid-cols-2">
   <div className="rounded-xl bg-white p-5 text-slate-900"><h3 className="flex items-center gap-2 font-semibold"><Server size={18} className="text-cyan-700"/>服务器配置</h3><div className="mt-3 space-y-2">{servers.length===0&&<p className="text-sm text-slate-400">尚未添加服务器配置</p>}{servers.map(s=><div key={s.id} className="flex justify-between rounded-lg border p-3"><div><b>{s.serverModel}</b><p className="text-xs text-slate-500">{s.quantity} 台 · CPU {s.cpuRequirement||'-'} · 内存 {s.memoryRequirement||'-'} · 存储 {s.storageRequirement||'-'}</p></div>{selected.status==='DRAFT'&&<button onClick={()=>removeServer(s.id)} className="text-red-500"><Trash2 size={16}/></button>}</div>)}</div>{selected.status==='DRAFT'&&<div className="mt-4 grid gap-3 sm:grid-cols-2">{[['serverModel','服务器型号'],['quantity','数量'],['cpuRequirement','CPU 要求'],['memoryRequirement','内存要求'],['storageRequirement','存储要求'],['networkRequirement','网络要求']].map(([k,l])=><label key={k} className="text-xs"><span>{l}</span><input type={k==='quantity'?'number':'text'} value={(serverForm as any)[k]} onChange={e=>setServerForm({...serverForm,[k]:k==='quantity'?Number(e.target.value):e.target.value})} className={inputClass}/></label>)}<button onClick={addServer} className="rounded-lg bg-cyan-700 px-4 py-2 text-sm font-semibold text-white sm:col-span-2">添加服务器配置</button></div>}</div>
   <div className="rounded-xl bg-white p-5 text-slate-900"><h3 className="flex items-center gap-2 font-semibold"><Boxes size={18} className="text-cyan-700"/>软件栈要求</h3><div className="mt-3 space-y-2">{software.length===0&&<p className="text-sm text-slate-400">尚未添加软件要求</p>}{software.map(s=><div key={s.id} className="flex justify-between rounded-lg border p-3"><div><b>{s.osName} {s.osVersion}</b><p className="text-xs text-slate-500">中间件 {s.middleware||'-'} · 数据库 {s.databaseRequirement||'-'}</p></div>{selected.status==='DRAFT'&&<button onClick={()=>removeSoftware(s.id)} className="text-red-500"><Trash2 size={16}/></button>}</div>)}</div>{selected.status==='DRAFT'&&<div className="mt-4 grid gap-3 sm:grid-cols-2">{[['osName','操作系统'],['osVersion','版本'],['middleware','中间件'],['databaseRequirement','数据库'],['licenseRequirement','许可要求'],['securityRequirement','安全要求']].map(([k,l])=><label key={k} className="text-xs"><span>{l}</span><input value={(softwareForm as any)[k]} onChange={e=>setSoftwareForm({...softwareForm,[k]:e.target.value})} className={inputClass}/></label>)}<button onClick={addSoftware} className="rounded-lg bg-cyan-700 px-4 py-2 text-sm font-semibold text-white sm:col-span-2">添加软件要求</button></div>}</div>
  </div></section>}

  {selectedProject&&canProcure&&<section className="mt-6 rounded-2xl border border-amber-200 bg-[#fffaf0] p-5 shadow-lg"><p className="text-xs font-bold uppercase tracking-[.22em] text-amber-700">Quotation Desk</p><h2 className="mt-1 text-xl font-semibold">{selectedProject.projectNo} · 供应商报价</h2><div className="mt-5 grid gap-5 xl:grid-cols-[1fr_.8fr]"><div className="space-y-3">{quotes.length===0&&<p className="rounded-lg border border-dashed border-amber-300 p-6 text-center text-sm text-slate-500">暂无报价</p>}{quotes.map(q=><div key={q.id} className="flex items-center justify-between rounded-xl border border-amber-200 bg-white p-4"><div><b>{q.supplierName}</b><p className="mt-1 font-mono text-lg">{q.currency} {Number(q.amount).toLocaleString()}</p><p className="text-xs text-slate-500">交期 {q.deliveryDate||'待定'} · {q.status}</p></div>{q.status==='SELECTED'?<CheckCircle2 className="text-emerald-600"/>:selectedProject.status!=='QUOTED'&&<button onClick={()=>selectQuote(q.id)} className="rounded-lg border border-amber-600 px-3 py-2 text-xs font-semibold text-amber-800">选定供应商</button>}</div>)}</div><div className="rounded-xl border border-amber-200 bg-white p-5"><h3 className="font-semibold">录入供应商报价</h3><div className="mt-3 grid gap-3 sm:grid-cols-2">{[['supplierName','供应商'],['amount','含税金额'],['currency','币种'],['deliveryDate','交付日期'],['validityDate','报价有效期']].map(([k,l])=><label key={k} className="text-xs"><span>{l}</span><input type={k.includes('Date')?'date':k==='amount'?'number':'text'} value={(quoteForm as any)[k]} onChange={e=>setQuoteForm({...quoteForm,[k]:e.target.value})} className={inputClass}/></label>)}<label className="text-xs sm:col-span-2"><span>备注</span><textarea value={quoteForm.notes} onChange={e=>setQuoteForm({...quoteForm,notes:e.target.value})} className={inputClass}/></label><button onClick={addQuote} className="rounded-lg bg-amber-600 px-4 py-2 text-sm font-semibold text-white sm:col-span-2">保存报价</button></div></div></div></section>}

  {show&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><div className="w-full max-w-2xl rounded-xl bg-white shadow-2xl"><div className="border-b px-6 py-5"><h2 className="text-lg font-semibold">新建服务器采购立项</h2></div><div className="grid gap-4 p-6 md:grid-cols-2">{[['customerName','客户名称'],['projectName','项目名称'],['quantity','服务器数量'],['requestedDeliveryDate','要求交期'],['deliveryLocation','交付地点']].map(([k,l])=><label key={k} className="text-sm"><span className="font-medium">{l}</span><input type={k==='quantity'?'number':k==='requestedDeliveryDate'?'date':'text'} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:k==='quantity'?Number(e.target.value):e.target.value})} className={inputClass}/></label>)}<label className="text-sm md:col-span-2"><span>服务器配置概要</span><textarea value={form.technicalSummary} onChange={e=>setForm({...form,technicalSummary:e.target.value})} className={inputClass}/></label><label className="text-sm md:col-span-2"><span>软件要求概要</span><textarea value={form.softwareSummary} onChange={e=>setForm({...form,softwareSummary:e.target.value})} className={inputClass}/></label></div><div className="flex justify-end gap-3 border-t bg-slate-50 px-6 py-4"><button onClick={()=>setShow(false)} className="rounded-lg border px-4 py-2 text-sm">取消</button><button onClick={create} className="rounded-lg bg-cyan-700 px-4 py-2 text-sm font-semibold text-white">保存草稿</button></div></div></div>}
 </div>;
};
export default SalesProcurement;
