# Use "rabbit" in production; "local" keeps development self-contained.
import.executor=local
import.queue=slss.production.import
rabbit.host=127.0.0.1
rabbit.port=5672
rabbit.username=guest
rabbit.password=guest
redis.host=127.0.0.1
redis.port=6379
redis.password=
